### ISSUE TITLE
Documentation update for use case 4

### ISSUE THREAD

**Issue by rhyswat** [logstash-plugins/logstash-filter-aggregate#100]
Just a thought on Use Case 4 in the documentation.

TLDR: `event.cancel()` can lose information from prior events with the same `task_id` 

Use Case 4 concerns events that come in some predictable order. The example given has `country_name` as the common field:

```
{ "country_name": "France", "town_name": "Paris" }
{ "country_name": "France", "town_name": "Marseille" }
{ "country_name": "USA", "town_name": "New-York" }
```

And the documentation correctly states that the two French towns are aggregated together.

But what if we had this, and wanted to a) aggregate towns but b) hold on to language:

```
{ "country_name": "France", "town_name": "Paris", language: "French" }
{ "country_name": "France", "town_name": "Marseille" }
{ "country_name": "USA", "town_name": "New-York" }
```

Could the documentation be updated to state that any data from prior events to be retained in the aggregate needs to be copied explicitly in the aggregation. Thus:

```
filter {
     aggregate {
       task_id => "%{country_name}"
       code => "
         map['country_name'] = event.get('country_name')

         # create a towns array as needed, and add to it
         map['towns'] ||= []
         map['towns'] << {'town_name' => event.get('town_name')}

        # copy any other data into the current aggregating map
        map['language'] ||= event.get('language')

         # this drops all data not copied over
         event.cancel()
       "
       push_previous_map_as_event => true
       timeout => 3
     }
   }
```

ending up with 

```
{ "country_name": "France", "towns": [ {"town_name": "Paris"}, {"town_name": "Marseille"} ], "language": "French" }
{ "country_name": "USA", "towns": [ {"town_name": "New-York"} ] }
```

Thoughts?

**Comment by fbaligand** [comment]
Hi, 

Well, the case you describe is exactly the same than field “country_name”. 
So the example already shows how to process single value fields and array fields.

**Comment by fbaligand** [comment]
Maybe I miss something and there is a difference. Tell me :)

**Comment by rhyswat** [comment]
There is a difference: language is *absent* from the second French record.

`event.cancel()` drops the information from the first French record unless it has been copied to `map`.

**Comment by fbaligand** [comment]
Well, indeed. 
But, you will have the same issue with whatever field, depending your personal use case. For instance, you could have « latitude » and « longitude » fields. 
This doc example is a simple example, that has to be adapted for each use case. 

That said, « country_name » is a nice « one-value »  field to demonstrate how to deal with « one-value » fields. 
But I won’t demonstrate every possible one-value field in an example. 

The only thing that could be relevant in this doc example is to replace « = » by « ||= » to tell that field is updated only once.

**Comment by rhyswat** [comment]
Events that do not have exactly the same structure are enough of a use case when you have a flow of "things" and "deltas to things".

I'm not trying to get you to document every conceivable case - I am asking for one sentence (and `||=`) for this use case.

**Comment by fbaligand** [comment]
OK. 
In that case, can you open a Pull Request to update the doc?

If you are not familiar with pull requests, don’t be afraid, there’s nothing complex. 
You can do it online easily, going on this page:
https://github.com/logstash-plugins/logstash-filter-aggregate/blob/master/docs/index.asciidoc
Click « edit » icon, update the doc in text area, and click on « update » button. Then follow the few wizard steps to submit the PR.

**Comment by rhyswat** [comment]
Sorry, the CLA signing screwed the commit.

**Comment by fbaligand** [comment]
OK. 
Thanks to have tried to submit the PR. 
If it’s ok for you, I will update the doc, getting inspired by your PR.

**Comment by fbaligand** [comment]
I just updated the docs, adding a remark about fields not always fulfilled.
I hope it matches your expectations :)

https://github.com/logstash-plugins/logstash-filter-aggregate/commit/1204131622077fd8fe49b22834bca09cbdb65fc5
