### ISSUE TITLE
[@metadata][something] missing in aggregated event

### ISSUE THREAD

**Issue by GERandro** [logstash-plugins/logstash-filter-aggregate#106]
Hi aggregate team

- Version: logstash 6.8.3
- Operating System: CENTOS 7

due to DSGVO rules we applied pseudonymization within the logstash pipeline for fields like [source_user_name] or [destination_user_name].
The logic is designed in a way to store the clear text value inside the logstash [@metadata][source_user_name] variable, where the field [source_user_name] is masked.
The aggregate filter is applied AFTER the pseudo tool, meaning there are several [@metadata][fields] available for each event.
Can you PLS highlight, if those special "[@metadata][fields]" are considered by the aggregate filter.
Within the output section of the logstash config I utilize the UDP output, to tranfer hash and value pairs to a pseudo cluster. For whatever reason the values are missing for aggregated events.

Thanks
Andro

**Comment by fbaligand** [comment]
Well, there’s nothing done in aggregate plugin except your `code` block. 
So if you want to copy event metadata fields to map (or the opposite), you have to explicitly write it in « code » block.

**Comment by GERandro** [comment]
Hi fbaligand

My aggregate `code` block has the objective to maintain all valuable fields incl. [@metadata][something] from the original events and count the aggregated events. 
This is the current implementation. Is there something missing to maintain the [@metadata][something] fields as well???:

Thanks Andro

````if [event_id] == "4672" {
 if [source_user_type] =~ "(machine|technicalaccount)" {
                aggregate {
                                timeout_timestamp_field => "timestamp"
                                task_id => "%{event_id}_%{host_hash}_%{privilege_list}_%{source_user_hash}"
                                code => "map['count'] ||= 0; map['count'] += 1
                                                map['event_start_time'] ||= event.get('timestamp')
                                                event.to_hash.each do |key,value|
                                                                                                if value.is_a?(Hash)
                                                                                                                                map[key] ||= {}
                                                                                                                               map[key].merge!(value)
                                                                                                  else
                                                                                                                map[key] = value
                                                                                                  end
                                                end
                                "
                                push_map_as_event_on_timeout => true
                                timeout_task_id_field => "~event_agg_hash"
                                timeout => 300
                                inactivity_timeout => 60
                                timeout_tags => ['aggregate']
                                timeout_code => "
                                                event.set('~event_agg', event.get('count') > 1)
                                                event.set('deltatime', Time.now.to_i - event.get('event_start_time').to_i)
                                "
                }
    } else {
  mutate { add_field => { "[@metadata][noAGG]" => "1" } } }
}

**Comment by fbaligand** [comment]
Well, I’m not sure that `event.data` returns @metadata. 
I invite you to check it. For example you can log it into console

**Comment by fbaligand** [comment]
Hi,

I invite you to try with this method: `event.to_hash_with_metadata`

**Comment by fbaligand** [comment]
Question is answered and there is no feedback since months, so I close the issue.
