### ISSUE TITLE
Logstash automatically loading the config file

### ISSUE THREAD

**Issue by avinaba91** [logstash-plugins/logstash-filter-aggregate#109]
Logstash is running via systemctl. It is loading the configuration file automatically after certain interval.So the Configuration file which contains an SQL query is loaded multiple times. JDBC plugin does not contain any schedule parameter.
I want my configuration file will be run only one time.(It will fetch all the data from database table and store it to elasticsearch).
What should I put in logstash.yml/pipeline.yml so that it will run once

https://discuss.elastic.co/t/logstash-automatically-loading-the-config-file/208790

**Comment by fbaligand** [comment]
This issue is not related at all to aggregate filter. 
So I close the issue.
