### ISSUE TITLE
Move `aggregate_maps_path` to pipeline settings?

### ISSUE THREAD

**Issue by fterrani** [logstash-plugins/logstash-filter-aggregate#124]
Hello everyone.

Currently, we have the constraint of [defining `aggregate_maps_path` only once](https://github.com/logstash-plugins/logstash-filter-aggregate/issues/26#issuecomment-217672373) in one of the aggregate filters since apparently, this feature is enabled or not per pipeline. I don't find this very convenient / clean / intuitive and this is the main reason I'm writing this issue. Has anyone similar feelings about this?

The first thing I would want to do in such a case is set `aggregate_maps_path` in the pipeline settings (`logstash.yml`, `pipelines.yml`...). I have the following in mind and am interested to know what you think about it:

- Since map persistence is defined per pipeline, I would add a new `pipeline.aggregate_maps_path` pipeline setting. This setting would by default point to Logstash's persistent data folder for people who don't care about where maps data is stored.
- Another boolean pipeline setting `pipeline.aggregate_maps_persistence` defaulting to `false` would allow to enable or not maps persistence. This would clearly express the intention to persist maps or not.
- Finally, I think the `aggregate_maps_path` filter option should be deprecated to avoid confusion and an error should occur if both `pipeline.aggregate_maps_path` pipeline setting and `aggregate_maps_path` filter option are defined.
- *Bonus question / idea:* has it been consider to define maps persistence per task? Do you think it could be interesting to have that choice?

**Comment by fbaligand** [comment]
Hi,

Well, to my knowledge, it is not possible to store plugin specific configuration into pipelines.yml or logstash.yml.
So, up to me, this is not feasible.

Then, setting `aggregate_maps_path` activates map persistence. I don't see the significant contribution of separating this option into two. Thus, it would generate a breaking change, what we try to avoid.

**Comment by fterrani** [comment]
Hi,

I see your point. Regarding this:

> Then, setting aggregate_maps_path activates map persistence. I don't see the significant contribution of separating this option into two. Thus, it would generate a breaking change, what we try to avoid.

Splitting into two different settings is interesting only if we allow a default value to the persistent data folder for `aggregate_maps_path` ***and*** if we move everything to pipeline settings. Otherwise this would be over the top indeed and induce a breaking change.

> Well, to my knowledge, it is not possible to store plugin specific configuration into pipelines.yml or logstash.yml.
So, up to me, this is not feasible.

I'm quite surprised by that! That really is a pity... Do you think it would be a valuable thing to have? E.g. a set of `filters.<filtername>.*` settings that would allow to configure `aggregate` and possibly other filters on a pipeline scope if needed? Can a filter access the pipeline configuration?

**Comment by fbaligand** [comment]
Well, to answer your last question, this is not related to plugin itself, but to Logstash core.
I'm the creator and maintainer of this plugin, but I'm not Elastic employee or Logstash core official maintainer.
You can ask the question as an issue in Logstash repository: https://github.com/elastic/logstash/issues

**Comment by fterrani** [comment]
Will do, thanks!
