### ISSUE TITLE
Problems with multiple worker threads

### ISSUE THREAD

**Issue by erik-stephens** [logstash-plugins/logstash-filter-aggregate#15]
Does the following look like user error or a bug?  With one worker, I see expected results:
```
$ ~/Downloads/logstash-2.0.0/bin/logstash -f /tmp/logstash.conf -w1 < /tmp/test.log
Default settings used: Filter workers: 1
Logstash startup completed
{
       "message" => "start: foo\n1\n2\n3\nfinished",
      "@version" => "1",
    "@timestamp" => "2015-11-13T19:10:02.312Z",
          "host" => "test",
         "count" => 4
}
{
       "message" => "start: bar\n1\n2\n3\n4\n5\nfinished",
      "@version" => "1",
    "@timestamp" => "2015-11-13T19:10:02.313Z",
          "host" => "test",
         "count" => 6
}
{
       "message" => "start: baz\n1\nfinished",
      "@version" => "1",
    "@timestamp" => "2015-11-13T19:10:02.313Z",
          "host" => "test",
         "count" => 2
}
Logstash shutdown completed
```

With multiple workers, results are all over the place:
```
$ ~/Downloads/logstash-2.0.0/bin/logstash -f /tmp/logstash.conf -w3 < /tmp/test.log
Default settings used: Filter workers: 3
Logstash startup completed
{
       "message" => "start: foo\n2\n3\nfinished",
      "@version" => "1",
    "@timestamp" => "2015-11-13T19:18:13.349Z",
          "host" => "test",
         "count" => 3
}
{
       "message" => "start: bar\n2\n1\n3\n4\n5\n1\nfinished",
      "@version" => "1",
    "@timestamp" => "2015-11-13T19:18:13.352Z",
          "host" => "test",
         "count" => 7
}
{
       "message" => "finished",
      "@version" => "1",
    "@timestamp" => "2015-11-13T19:18:13.351Z",
          "host" => "test"
}
Logstash shutdown completed
```

test.log:
```
start: foo
1
2
3
finished
start: bar
1
2
3
4
5
finished
start: baz
1
finished
```

logstash.conf:
```
input {
  stdin {}
}
output {
  stdout {
    codec => rubydebug { metadata => true }
  }
}
filter {
  mutate {
    replace => {
      'host' => 'test'
    }
  }
  if [message] =~ /^start/ {
    aggregate {
      task_id => '%{host}:test'
      code => "map['msgs'] = [event['message']]; map['count'] = 0;"
      map_action => 'create'
    }
    drop {}
  }
  else {
    aggregate {
      task_id => '%{host}:test'
      code => "map['msgs'] << event['message']; map['count'] += 1;"
      map_action => 'update'
    }
  }
  if [message] =~ /^finish/ {
    aggregate {
      task_id => '%{host}:test'
      code => 'event["message"] = map["msgs"].join("\n"); event["count"] = map["count"];'
      map_action => 'update'
      end_of_task => true
    }
  }
  else {
    drop {}
  }
}
```

**Comment by fbaligand** [comment]
Hi @erik-stephens,

When you use multiple workers (so multiple threads in parallel), you have no guarantee on the order of arrival of events.
So aggregate filter could process firstable event "2" and then event "1".
That's what happens in your second result document.
And in your third result document, the "finished" event is processed before "start" event so you get only "finished" as result "message" field (no aggregation is done because "map_action=update" condition is not met).

So, because aggregate filter is dependant from order of arrival of events, you have to use only one worker to have a nice behaviour.

A tip that I can give to you to have multiple events processed at the same time (for performance needs) : you could start several logstash instances, each instance will read one input (on file, one tcp port, ...). Like that each instance has one worker ; but globally, you have as many workers as logstash instances.

**Comment by erik-stephens** [comment]
I saw the mutex code and thought that was to support multiple worker threads.  Do you or anyone else know what that is for?  I want to make sure I understand that when working on #14.  Thanks.

**Comment by fbaligand** [comment]
Hi @erik-stephens,

Actually, I am the creator of this plugin, so I know very well each line of code ;)
Globally (not just for this plugin), Thread-safety is something important to me. 
So, from the beginning, I make the plugin code thread-safe. 
It could be really useful if you can be sure that for one task id, all related events happen in the right order into aggregate plugin. 
But presently, it is not the case. 

There are some plans in logstash roadmap to support multiple pipelines in one logstash instance. 
This could be a start point for that. 

I would really enjoy, if I could specify one worker thread per tag, given that tag is positioned by input. Using that, I could really support multiple workers. 

But today, technically, code is thread-safe (it won't raise an exception with multiple threads), but functionally, it is not thread-safe.

**Comment by erik-stephens** [comment]
Thanks for the explanation.  I think I understand now.
