### ISSUE TITLE
SSLSocket#session= is not supported

### ISSUE THREAD

**Issue by robin13** [logstash-plugins/logstash-filter-aggregate#20]
When installing, this warning is printed

```
root@rcl-nas:logstash# ./bin/plugin install logstash-filter-aggregate
Validating logstash-filter-aggregate
Installing logstash-filter-aggregate
WARNING: SSLSocket#session= is not supported
Installation successful
```

**Comment by fbaligand** [comment]
Hi @robin13,

logstash-filter-aggregate don't use SSL at all.
I presume it's a warning about downloading the plugin on rubygems.org using https.

So I don't think this warning is tied to logstash-filter-aggregate plugin itself.

Finally, given the last log line, the installation is successful :)

**Comment by robin13** [comment]
It probably is due to the downloading, but still - any warnings during installation are unsettling.  Any idea how come it happens with this plugin, but not with others?

**Comment by fbaligand** [comment]
Hi @robin13,

I'm very surprised about that warning for this plugin but not for others.

I just tried to reproduce your problem (using windows) and it worked just fine without warning :
```
C:\tools\logstash\logstash-2.1.1\bin>plugin install logstash-filter-aggregate
io/console not supported; tty will not be manipulated
Validating logstash-filter-aggregate
Installing logstash-filter-aggregate
Installation successful
```

Precision : the last aggregate release published on rubygems.org has been made using logstash-plugins jenkins automated job.
Usually, I make the release for myself, on my computer. Maybe it is the cause.
But that's weird, because their automated job should be better.

**Comment by robin13** [comment]
Tested again now, and the error did not occur this time... perhaps the new version of the plugin fixed this?

**Comment by fbaligand** [comment]
The last release (2.0.3) was on November 3rd 2015. 
So before you open this issue.

**Comment by robin13** [comment]
Strange....

**Comment by fbaligand** [comment]
As you say :)

**Comment by geekpete** [comment]
I still see this error with logstash 2.3.2 with the following JDK version:

```
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK Zero VM (build 25.45-b02, interpreted mode)
```

on ARM architecture:

```
Linux www1 4.1.6-249 #1 SMP Mon Aug 31 12:34:47 UTC 2015 armv7l armv7l armv7l GNU/Linux
```

**Comment by fbaligand** [comment]
If you have this problem with translate plugin, I invite you to open an issue on translate github repository.

**Comment by jordansissel** [comment]
This warning is harmless and not related to the aggregate filter. It has to
do with JRuby's tls library.

It is safe to ignore this warning.

**Comment by cutd** [comment]
```
Step 2 : RUN logstash-plugin install --version 5.0.0 logstash-input-kafka
 ---> Running in 32fa66c5f699
Validating logstash-input-kafka-5.0.0
Installing logstash-input-kafka
WARNING: SSLSocket#session= is not supported
```
When I install this plugin its wait a long long long time.

**Comment by fbaligand** [comment]
Hi,

As it is not an issue associated to aggregate plugin, I invite you to open an issue on elastic/logstash github repository. 

Fabien
