### ISSUE TITLE
Aggregate seemingly not working

### ISSUE THREAD

**Issue by berfarah** [logstash-plugins/logstash-filter-aggregate#23]
Hey, I was wondering if someone could tell me what I'm doing wrong with my aggregate config here. I keep getting all the messages separately, and I can't figure out for the life of me why they're not aggregating:

Example input:
```
INFO  [2016-03-11 08:13:05] : @0123456789123.jpg Found file!
WARN  [2016-03-11 08:13:05] : @0123456789123.jpg Upscaling (is 500x500, must be 500x500)
DEBUG [2016-03-11 08:13:05] : @0123456789123.jpg No swatch to crop
DEBUG [2016-03-11 08:13:05] : @0123456789123.jpg Skipped Image derivative: 2000 (image too small)
DEBUG [2016-03-11 08:13:05] : @0123456789123.jpg Skipped Image derivative: 1500 (image too small)
DEBUG [2016-03-11 08:13:05] : @0123456789123.jpg Skipped Image derivative: 900 (image too small)
DEBUG [2016-03-11 08:13:05] : @0123456789123.jpg Made Image derivative: 500
DEBUG [2016-03-11 08:13:05] : @0123456789123.jpg Made Image derivative: 450
DEBUG [2016-03-11 08:13:05] : @0123456789123.jpg Made Image derivative: 400
DEBUG [2016-03-11 08:13:05] : @0123456789123.jpg Made Image derivative: 300
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 275
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 215
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 180
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 150
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 100
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 80
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 75
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 70
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 60
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 45
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 40
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 30
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 18
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Made Image derivative: 16
DEBUG [2016-03-11 08:13:06] : @0123456789123.jpg Backing up to /data/backup
INFO  [2016-03-11 08:13:06] : @0123456789123.jpg It took 1.2s to complete operations

```

```
input { stdin {} }

filter {
  grok { match => ["message", "(?<severity>[A-Z]+)\s{1,4}\[(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\] : (@(?<file>\d{13}(_AV\d*)?(\.\w{2,4})?))? ?(?<rest>.+)"] }
    # Timestamp matching and override
    date { match => ["timestamp", "yyyy-MM-dd HH:mm:ss"] }
    mutate {
      replace => { "message" => "%{rest}" }
      remove_field => ["rest"]
    }

    if [severity] == "FATAL" { mutate { add_field => { "error" => "%{message}" } } }

    if [message] =~ "Found file" {
      aggregate {
        task_id => "%{file}"
        code => ""
        map_action => "create"
      }
    }

    # Create tags based on whether it has a swatch
    if [message] =~ "Swatch found" { mutate { add_field => { "swatch" => "true"  } } }
    if [message] =~ "No swatch"    { mutate { add_field => { "swatch" => "false" } } }

    # Detect if upscaled, add tag
    if [message] =~ "Upscaling" {
      grok {
        match => ["message", "is (?<upscaled_from>\d+x\d+)"]
        add_tag => ["upscaled"]
      }
    }

    # For derivatives, get the type and size of derivative
    if [message] =~ "derivative: " {
      grok { match => ["message", "(?<derivative>(Image|Swatch)) derivative: (?<size>\d+(_SW)?)"] }

      aggregate {
        task_id => "%{file}"
        code => "map['d'] ||= {}; map['d']['%{derivative}'] ||= {}; map['d']['%{derivative}']['%{size}'] = ('%{message}' !~ /^Skipped/)"
        map_action => "update"
      }
    }

    if ([message] =~ "It took") or ([severity] == "ERROR") {
      if [severity] == "ERROR" {
        grok {
          match => ["message", "to errors: (?<error>.+)"]
          add_field => { "error" => "%{error}" }
        }
      } else {
        grok { match => ["message", "It took (?<processing_time>[\d\.]+?)s"] }
      }

      aggregate {
        task_id => "%{file}"
        code => ""
        # timeout => 90
        map_action => "update"
        end_of_task => true
      }

    }
  }
}

output { stdout { codec => rubydebug } }
```

**Comment by alkuzad** [comment]
Are you using Logstash > 2.0 ? If yes do you use "-w 1" option to use only one filter worker ?

**Comment by fbaligand** [comment]
After tests, I saw several fixes :
- first, you have to remove last `}` before output.
- then you have to replace :
`code => "map['d'] ||= {}; map['d']['%{derivative}'] ||= {}; map['d']['%{derivative}']['%{size}'] = ('%{message}' !~ /^Skipped/)"`
by :
`code => "map['d'] ||= {}; map['d'][event['derivative']] ||= {}; map['d'][event['derivative']][event['size']] = ('%{message}' !~ /^Skipped/)"`
- finally, in your last aggregate filter, you must set this code option :
`code => "event['d'] = map['d']"`

Doing that, it works on my machine.
Tell me if works also on yours :)

**Comment by berfarah** [comment]
Thank you @fbaligand, I don't think I would have figured it out on my own. That was very helpful! The last `}` was definitely a copy-paste error, but the other two points were immensely useful!

I'm still getting the separate events up to the aggregate (each log  - is there a way to prevent them from firing, or is that just going to show up in rubydebug?

**Comment by fbaligand** [comment]
Happy to see I helped you :)

Concering the "previous" events, it's normal that they are still there.
Actually, aggregate filter collect information among several events to aggregate them into final event. But it does not drop previous events. It's not its role neither its aim.
For some cases (especially mines), it's useful to keep these previous events.

So if you don't want these intermediate events, you have to use `drop` filter, right after `aggregate` plugin.

**Comment by berfarah** [comment]
Huge thanks! For me it depended, so `drop {}` was perfect :) I have great logging now, thanks to your help!!!

**Comment by fbaligand** [comment]
Happy to have helped you :)
And happy to see aggregate plugin is useful to you !

**Comment by swapnilkeskar** [comment]
Hi,
I'm new to aggregate filter, wanted to group logs based on correlation id for logs
log data is as below
2017-07-06 06:45:27,428 [11] INFO - 0HL647AA5D3AR - VM - MyApplication - Details 1
2017-07-06 06:45:27,428 [11] INFO - 0HL647AA5D3BR - VM - MyApplication - Details 2
2017-07-06 06:45:27,428 [11] INFO - 0HL647AA5D3AR - VM - MyApplication - Details 3
2017-07-06 06:45:27,428 [11] INFO - 0HL647AA5D3BR - VM - MyApplication - Details 4
2017-07-06 06:45:27,428 [11] INFO - 0HL647AA5D3WR - VM - MyApplication - Details 5
2017-07-06 06:45:27,428 [11] INFO - 0HL647AA5D3WR - VM - MyApplication - Details 6

I'm using filter as below but could not group logs based on trace id.

grok {
     match => [ "message", "%{LOGLEVEL:loglevel} - %{NOTSPACE:taskid} - %{NOTSPACE:logger} - %{WORD:label}( - %{INT:duration:int})?" ]
   }
   if [loglevel] == "INFO" {
     aggregate {
        task_id => "%{taskid}"      
        code => ""
        # timeout => 90
        map_action => "update"
        end_of_task => true
     }
   } 

Any help would be great on what I'm missing here.

Thanks,

**Comment by fbaligand** [comment]
If you have questions or need help, please post a topic here : https://discuss.elastic.co/c/logstash
