### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-filter-aggregate#24]
http://build-eu-1.elasticsearch.org/job/logstash-plugin-filter-aggregate-unit/jdk=JDK7,nodes=metal-pool/18/console

/cc @fbaligand

**Comment by fbaligand** [comment]
@suyograo 
Let me guess : the tests were ran using Logstash 3.0 ?
And the event timestamp format object has changed ?

**Comment by simpleuser99** [comment]
Hello fbaligand when planning to implement support logstash 5?

**Comment by fbaligand** [comment]
@simpleuser99 
I currently work on this issue.
It should be released soon. I think, this week.

**Comment by simpleuser99** [comment]
@fbaligand in 5.0.0 ver We still have to use 1 worker?

**Comment by fbaligand** [comment]
Yes.
Whatever Logstash version you have, aggregate plugin need that logs are processed in the right order.
And given Logstash pipeline architecture, the only way to do that is to use 1 worker.

**Comment by fbaligand** [comment]
@simpleuser99 
Logstash 5 support has just been fixed with release v2.5.0.
Tell me if it works fine for you.

**Comment by fbaligand** [comment]
@suyograo 
Today, tests don't work because java 7 is used at runtime and something (not aggregate plugin) needs java 8 (java byte code version 52.0)

**Comment by fbaligand** [comment]
Fixed by PR #47
