### ISSUE TITLE
Option to store aggregate map to file that can be loaded upon logstash restart

### ISSUE THREAD

**Issue by doingitbigdata** [logstash-plugins/logstash-filter-aggregate#26]
I am currently using the aggregate plugin to read headers which can change dynamically in a file and correlate them to the data that follows.

An issue I have is if logstash is stopped and restarted the existing map data is lost from memory and therefore I cannot correlated the processed events to their appropriate header.

Would it be possible to create an enhancement which stores the map data to a file that can be reloaded upon a logstash restart? Are there any other suggestions?

**Comment by fbaligand** [comment]
Hi, 
This feature request is clearly relevant.
To be honest, I had already thought about such a feature.

**Comment by fbaligand** [comment]
Sorry, I closed the issue by mistake.

**Comment by mrchang7** [comment]
+1. 
I'm also hitting to this problem in putting this plugin into production and it's real headache. I also have to say I love the aggregate. Thanks!

**Comment by fbaligand** [comment]
Nice news guys : I plan to make a new release really soon, that will solve this problem !

**Comment by fbaligand** [comment]
Release 2.1.0 is done !

It adds a new option "aggregate_maps_path" to fix this issue. 

Here's the doc for this option (also available on readme page) :
The path to file where aggregate maps are stored when logstash stops and are loaded from when logstash starts.
If not defined, aggregate maps will not be stored at logstash stop and will be lost.
Should be defined for only one aggregate filter (as aggregate maps are global).
Example value : "/path/to/.aggregate_maps"

I invite you to test it and give feedback :)

**Comment by mrchang7** [comment]
Cool man! Can't wait to test it!

**Comment by fbaligand** [comment]
Cool. 
Tell me back if it works as expected !

**Comment by mrchang7** [comment]
Tested. The new plugin generates the aggregate_maps file but it doesn't parse after restart; without the map it throws out errors as before. Sorry but can't share the code here.

I tested as putting the new option in all create/update aggregates. Divided a data file into two, where the maps for some data in the second file should be found in the first file.

**Comment by fbaligand** [comment]
The option should be set to only one aggregate filter, as aggregate maps are global (static).
After restart, aggregate plugin should load the file, and then delete it.
Is the file deleted after restart ?
Do you see any error stack ?
Which OS do you use ?

**Comment by mrchang7** [comment]
I made a mistake by testing two files... as the map was created by file path itself. 

Now, it's working perfect. Thanks a lot fbaligand for your quick response today!

**Comment by fbaligand** [comment]
Nice news !
Happy to see it works perfeclty !

For the quick response, to be honnest, I was working on the feature for a week, and your comment comes when I finished :)
But your comment motivated me to quickly release !
And thank you for your quick feedback !

I had written in documentation, that only one filter should have this option, but given your feedback, I will maybe make a 2.1.1 release which checks if there are 2 filters configured with this option, and if so, raises an error.

**Comment by fbaligand** [comment]
Now that feature is released and validated by @mrchang7, I close the issue.

**Comment by doingitbigdata** [comment]
Awesome. I've also confirmed that this works. I would like to understand functionally when the aggregate maps file is written to. Is it when the instance of the aggregate filter where the aggregate_maps_path is specified is invoked? Or when logstash is stopped?

**Comment by fbaligand** [comment]
Hi @doingitbigdata ,
Happy to see it works also for you !

To answer your question, file is written when logstash stops.
In fact, when logstash stops, it calls close() method of every plugin. It's here I store aggregate maps into file.

**Comment by fbaligand** [comment]
For information, I just made a new release 2.1.1, with :
- when "aggregate_maps_path" option is defined in more than one aggregate filter, raise a Logstash::ConfigurationError
- add support for logstash hot reload feature
