### ISSUE TITLE
Plugin fails verification during install

### ISSUE THREAD

**Issue by jjfalling** [logstash-plugins/logstash-filter-aggregate#3]
When installing this plugin via either a local gem or ruby gems, the plugin fails verification. 
Tested on LS 1.5.0 and 1.5.2.

**Comment by fbaligand** [comment]
Can you give more details ?
OS, java version, and especially error logs.

**Comment by jjfalling** [comment]
Actually, it looks like the plugin was from another vendor but the referenced this repo and used the same name. Closing the issue.

**Comment by fbaligand** [comment]
Interesting...
Can you give more info (url for example) about this "another plugin from another vendor" ?
