### ISSUE TITLE
Read code from a ruby file.

### ISSUE THREAD

**Issue by estebanz01** [logstash-plugins/logstash-filter-aggregate#35]
I'm confused about the feature request, so I'm creating an issue. Feel free to close it if this doesn't belong here.

For the sake of testing purposes, I want to be able to write something like this:
```bash
filter {
  aggregate {
    task_id => "%{my_beautiful_group_field}"
    code => "/my/absolute/path/to/a/tested/file.rb"
  }
}
```

I can fork the code and submit a PR, but I don't know if that's the common process to do it.

Let me know what you think.

Cheers.

**Comment by fbaligand** [comment]
Hi,

To open a feature request, that's the right way : bug reports and feature requests are open using the same way, that is, opening an issue here.

You can fork the code and make a PR. That's the common way to propose an code enhancement.

Concerning this specific feature, I think it would be fine to add new option called "code_path", which references the file to load.
And then, either code or code_path option must be set.

But this feature brings some questions :
- what is the structure of referenced file ? Normally, a .rb file represents a class, with methods and properties. So which class ? Which method ?
- And then, you have to load a class which is not in logstash class path. So how to load it ?

**Comment by estebanz01** [comment]
Well, you bring some valid questions which I wasn't consider before.

I was thinking in load a file with the snippet that will be embedded in the code param and avoid having a really big chunk of code in the config file.

For some reason, I ended up with the following config:
```bash
filter {
  aggregate {
    task_id => "%{group_id}"
    code => "map['user_count'] ||= 0
             map['event_count'] ||= 0
             case event['state']
             when 'delete', 'transfer'
               map['user_count'] -= (map['user_count'] == 0 ? 0 : 1)
             when 'create'
               map['user_count'] -= (map['user_count'] == 0 ? 0 : 1)
             end
             
             map['event_count'] += 1
             if map['event_count'] == 3
               map['event_count'] = 0
               event['user_count'] = map['user_count']
             end"
  }
```

So wanted to put that piece of code in a `file.rb`, making easier the code to be tested and debugged, ending with two files:

```ruby
map['user_count'] ||= 0
map['event_count'] ||= 0

case event['state']
when 'delete', 'transfer'
  map['user_count'] -= (map['user_count'] == 0 ? 0 : 1)
when 'create'
  map['user_count'] -= (map['user_count'] == 0 ? 0 : 1)
end
             
map['event_count'] += 1
if map['event_count'] == 3
  map['event_count'] = 0
  event['user_count'] = map['user_count']
end
```

```bash
filter {
  aggregate {
    task_id => "%{group_id}"
    code_path => "/path/to/file.rb"
  }
}
```

Maybe `.rb` is not the correct extension to be used in this case (`.erb` maybe?).

**Comment by alkuzad** [comment]
Why you don't just use require?

13.07.2016 19:40 "Esteban Zapata Rojas" <notifications@github.com>
napisał(a):

**Comment by estebanz01** [comment]
It does not work, I get the following exception:
```
Aggregate exception occurred.
Error: undefined local variable or method 'map' for main:Object;
Code: require '/etc/logstash/test.rb' ;
Map: {} ; EventData: {"message"=>"delete - 1", "@version"=>"1" ... } {:level=>:error}
```

**Comment by alkuzad** [comment]
yep, you have to use library in some way, require just loads code for use:

`require '/a/b/c/foo.rb'; a = Bar::Baz.new(map, event); a.regex_map_add('Status.*?:\s*(?<value>.*)', 'status'); map.merge!(a.map)"`

In this example I run method manually but object could do everything in init.

**Comment by fbaligand** [comment]
I like @alkuzad suggestion.
Using that, you can do whatever you need. You can eventually use a class method to avoid instanciate a new instance each time.

Creating a new option for that seems not to be a good idea, given the questions I asked before. 
It would involve a too complex enhancement and would be less flexible than @alkuzad 's solution.

**Comment by fbaligand** [comment]
@estebanz01 

To make work your code, you have to define a valid class in your .rb file.

For example : 
``` ruby
class MyAggregateCode
    def self.aggregate(event, map)
        <your code>
    end
end
```

And then call it like that :
`code => "require '/yourfile.rb' ; MyAggregateCode.aggregate(event, map)"`

**Comment by estebanz01** [comment]
Interesting approach. I'll check during the day and let you know. thanks for your help :)

**Comment by estebanz01** [comment]
that did the trick. Thanks guys for your feedback.

**Comment by fbaligand** [comment]
@estebanz01
Nice to see it fixes your problem :)

**Comment by alexpop** [comment]
Similar to Fabien's, but pointing to a ruby file stored in the config directory:

```
      code => "
        require ENV['LOGSTASH_CONFIG_DIR']+'/ruby/yourfile.rb'
        MyAggregateCode.aggregate(event, map)
     "

```
