### ISSUE TITLE
help with the codec option aggregate plugin

### ISSUE THREAD

**Issue by simpleuser99** [logstash-plugins/logstash-filter-aggregate#39]
Hello. I understand that my post is not issue in the conventioanl sense. But I need help and I don't know where can I go. I need use aggregate plugin, but I don't know ruby. So I can not properly describe the codec option. I would be very grateful if anyone can help me do it.
I have the next case:
Hi All,

I am having hard times trying to merge multi-line Postgresql logs with GROK into one Logstash event.

My log file look like this:

> Jul 22 17:03:27 my.host example.com[24977]: [137-1] 2016-07-22 17:03:27.339 MSK  User: username  Database: my_db  Host: 192.168.0.52(38494)  Proc ID: 24977  etc1
> Jul 22 17:03:27 my.host example.com[24977]: [137-2] 2016-07-22 17:03:27.339 MSK  User: username  Database: my_db  Host: 192.168.0.52(38494)  Proc ID: 24977  etc2
> Jul 22 17:03:27 my.host example.com[24597]: [2953-1] 2016-07-22 17:03:27.339 MSK  User: username  Database: my_db  Host: 192.168.0.52(38053)  Proc ID: 24597  etc
> Jul 22 17:03:27 my.host example.com[3637]: [3779-1] 2016-07-22 17:03:27.340 MSK  User: username  Database: my_db  Host: 192.168.0.52(17809)  Proc ID: 3637  etc
> Jul 22 17:03:27 my.host example.com[24977]: [138-1] 2016-07-22 17:03:27.339 MSK  User: username  Database: my_db  Host: 192.168.0.52(38494)  Proc ID: 24977  etc1
> Jul 22 17:03:27 my.host example.com[3637]: [3780-1] 2016-07-22 17:03:27.340 MSK  User: username  Database: my_db  Host: 192.168.0.52(17809)  Proc ID: 3637  etc
> Jul 22 17:03:27 my.host example.com[24977]: [138-2] 2016-07-22 17:03:27.339 MSK  User: username  Database: my_db  Host: 192.168.0.52(38494)  Proc ID: 24977  etc2 
> Jul 22 17:03:27 my.host example.com[24977]: [139-1] 2016-07-22 17:03:27.340 MSK  User: username  Database: my_db  Host: 192.168.0.52(38494)  Proc ID: 24977  etc
> Jul 22 17:03:27 my.host example.com[24597]: [2954-1] 2016-07-22 17:03:27.340 MSK  User: username  Database: my_db  Host: 192.168.0.52(38053)  Proc ID: 24597  etc
> Jul 22 17:03:27 my.host example.com[24597]: [2954-2] #011 SELECT count(*) FROM table#015

I try to use:

> multiline {
> pattern => "... [\d+-1]" 
> negate => true
> what => "previous"
> }

but I have:

> line 1: ...[137-1] and [137-2]...
> line 2: ...[2953-1]...
> line 3: ...[3779-1]...
> line 4: ...[138-1]...
> line 5: ...[3780-1] and [138-2]...
> line 6: ...[139-1]...
> line 7: ...[2954-1]...

That's not what I need. I want:

> line 1: ...[137-1] and [137-2]...
> line 2: ...[2953-1]...
> line 3: ...[3779-1]...
> line 4: ...[138-1] and [138-2]...
> line 5: ...[3780-1]...
> line 6: ...[139-1]...
> line 7: ...[2954-1]...

or

> line 1: ...[137-1] and [137-2]...
> line 2: ...[2953-1]...
> line 3: ...[3779-1]...
> line 4: ...[3780-1]...    
> line 5: ...[138-1] and [138-2]...
> line 6: ...[139-1]...
> line 7: ...[2954-1]...

I understand that aggregate plugin help me. But I don't understand how I can use it.
Thanks

**Comment by untergeek** [comment]
> But I need help and I don't know where can I go.

The appropriate place for usage questions is https://discuss.elastic.co/c/logstash

Feel free to copy and paste the question there.

**Comment by simpleuser99** [comment]
I post the question https://discuss.elastic.co/t/specific-grok-filter-for-multi-line-postgresql-log/56286
but I haven't help

**Comment by simpleuser99** [comment]
After much effort, I made such a configuration:
> filter {
>                 grok {
>                         match => [ "message", "%{SYSLOGTIMESTAMP:timestamp} %{SYSLOGHOST:logsource} %{SYSLOGPROG}: \[%{INT:line}-%{INT:part_of_line}] %{GREEDYDATA:ostatok}" ]
>                 }
> 
>         aggregate {
>                 task_id => "%{line}"
>                  code =>  "map['full_message'] ||= '' ; map['full_message'] += event['ostatok'] ; event['full_message'] ||= '' ; event['full_message'] = map['full_message']"
>                }
> }

But I have next event on elasticsearch:

> event 1: ...[137-1]...
> event 2: ...[137-1] and [137-2]...
> event 3: ...[2953-1]...
> event 4: ...[3779-1]...
> event 5: ...[138-1]...
> event 6: ...[138-1] and [138-2]...
> event 5: ...[3780-1]...
> event 6: ...[139-1]...
> event 7: ...[2954-1]...
> event 8: ...[2954-1] and [2954-2]...

How I can clean my events from event 1: ...[137-1]..., event 5: ...[138-1]..., event 7: ...[2954-1]... ?
