### ISSUE TITLE
Unexpected behaviour of timeout parameter

### ISSUE THREAD

**Issue by doingitbigdata** [logstash-plugins/logstash-filter-aggregate#40]
I'm experiencing unexpected behavior of the timeout parameter.

I've set the logstash parameter as follows:

timeout => 86400

Which should correspond to 1 day, but I'm seeing that it is expiring about 1 hr and 20 min after creating the task. 

My questions about this parameter are:

1. For a given task_id, does it matter what aggregate code block contains the timeout parameter (e.g. create, update, end_of_task etc.)? Is it ok if it is in multiple aggregate code blocks?

2. If there are multiple tasks (different task_ids) with different desired timeout parameters could they interfere with each other somehow?  

3. What happens if timeout is set to 0?

As a sidenote I believe the info provided here is out of date as the default is 1800 not 0:
https://www.elastic.co/guide/en/logstash/current/plugins-filters-aggregate.html#plugins-filters-aggregate-timeout

I'm using logstash v2.3.2

**Comment by fbaligand** [comment]
1. timeout parameter should be defined only one time, i.e. in one aggregate filter. If it is defined  on several aggregate filters, the min  value is chosen. So if you have one aggregate filter with timeout set to 1h20m, it could explain your problem. 

2. Today, there is no "timeout by task_id pattern" feature. If you're interested by such a feature, you can open an issue to ask this. Today, as explained in point 1, there is only one timeout defined for all aggregate filters. 

3. In last plugin version (and last doc) there is no default value, which is confusing. And timeout=0 is considered as no specific timeout defined. So either default timeout either timeout defined in another aggregate filter. 

Actually, "current" logstash official doc is not up to date. The last doc version is here :
https://www.elastic.co/guide/en/logstash/master/plugins-filters-aggregate.html#plugins-filters-aggregate-timeout
Globally, to be sure to have last doc version, I invite you to read aggregate's github readme page, which is always up to date.

**Comment by doingitbigdata** [comment]
Thanks for the clarification. 

Our issue seems because we assumed it was possible to have a different timeout by task_id.

**Comment by fbaligand** [comment]
OK. 
If you wish such a feature, please open an issue to ask for it.
And if all your questions are answered, please close this issue.
