### ISSUE TITLE
Help me please with ruby code for aggregate complex multiline postgresql log

### ISSUE THREAD

**Issue by simpleuser99** [logstash-plugins/logstash-filter-aggregate#41]
> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
I'm sorry. But the https://discuss.elastic.co/c/logstash has limit of symbols and I can't create my question.
Dear Fabien Baligand helped me once in this topic https://discuss.elastic.co/t/specific-grok-filter-for-multi-line-postgresql-log/56286/12 , for which he thanks a lot.

But nfortunately, after a time, I realized that I did not get the right result. My logs proved to be more complicated than I had imagined them. And I describe my problem more fully.
My log look like this:
> Aug 11 11:34:53 server5 marker2[21881]: [35-1] 2016-08-11 11:34:53.021 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  operator: SQL_QUERY1 pdo_stmt_00000004
> Aug 11 11:34:53 server5 marker2[21881]: [36-1] 2016-08-11 11:34:53.021 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  duration: 0.032 ms
> Aug 11 11:34:53 server8 marker3[19238]: [29-1] 2016-08-11 11:34:53.020 MSK  User: user2  Database: my_db2  Host: 192.168.50.11(17050)  Proc ID: 19238  app_name2 LOG:  operator: SQL_QUERY1 pdo_stmt_00000002
> Aug 11 11:34:53 server5 marker2[21878]: [85-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62679)  Proc ID: 21878  app_name3 LOG:  duration: 0.118 ms, разбор pdo_stmt_0000000d: SQL_QUERY2
> Aug 11 11:34:53 server8 marker3[19238]: [30-1] 2016-08-11 11:34:53.020 MSK  User: user2  Database: my_db2  Host: 192.168.50.11(17050)  Proc ID: 19238  app_name2 LOG:  duration: 0.036 ms
> Aug 11 11:34:53 server5 marker2[21877]: [125-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62677)  Proc ID: 21877  app_name4 LOG:  operator: SQL_QUERY1 pdo_stmt_00000013
> Aug 11 11:34:53 server5 marker2[21877]: [126-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62677)  Proc ID: 21877  app_name4 LOG:  duration: 0.039 ms
> Aug 11 11:34:53 server5 marker2[21872]: [181-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 LOG:  duration: 0.123 ms, разбор pdo_stmt_0000001d: SQL_QUERY3_part1
> Aug 11 11:34:53 server5 marker2[21872]: [181-2] SQL_QUERY3_part2$a
> Aug 11 11:34:53 server1 marker10[29370]: [18189-1] 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(26091)  Proc ID: 29370  [n/d] LOG:  operator: SQL_QUERY4
> Aug 11 11:34:53 server5 marker2[21881]: [37-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  duration: 0.057 ms, разбор pdo_stmt_00000005: SQL_QUERY4$a$b$c
> Aug 11 11:34:53 server5 marker2[21878]: [86-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62679)  Proc ID: 21878  app_name3 LOG:  duration: 0.335 ms, LOG Bind pdo_stmt_0000000d: SQL_QUERY2
> Aug 11 11:34:53 server5 marker2[21878]: [87-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62679)  Proc ID: 21878  app_name3 LOG:  do pdo_stmt_0000000d: SQL_QUERY2
> Aug 11 11:34:53 server1 marker10[29370]: [18190-1] 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(26091)  Proc ID: 29370  [n/d] LOG:  duration: 0.247 ms
> Aug 11 11:34:53 server5 marker2[21878]: [88-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62679)  Proc ID: 21878  app_name3 LOG:  duration: 0.067 ms
> Aug 11 11:34:53 server5 marker2[21877]: [127-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62677)  Proc ID: 21877  app_name4 LOG:  duration: 0.056 ms, разбор pdo_stmt_00000014: 
> Aug 11 11:34:53 server5 marker2[21877]: [127-2] SQL_QUERY5_part1
> Aug 11 11:34:53 server5 marker2[21877]: [127-3] SQL_QUERY5_part2
> Aug 11 11:34:53 server12 marker10[16792]: [15470-1] 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(61603)  Proc ID: 16792  [n/d] LOG:  operator: SQL_QUERY8_part1
> Aug 11 11:34:53 server12 marker10[16792]: [15470-2] SQL_QUERY8_part2
> Aug 11 11:34:53 server12 marker10[16792]: [15470-3] SQL_QUERY8_part3
> Aug 11 11:34:53 server12 marker10[16792]: [15470-4] SQL_QUERY8_part4
> Aug 11 11:34:53 server5 marker2[21877]: [127-4] SQL_QUERY5_part3
> Aug 11 11:34:53 server5 marker2[21877]: [127-5] SQL_QUERY5_part4
> Aug 11 11:34:53 server5 marker2[21877]: [127-6] SQL_QUERY5_part5
> Aug 11 11:34:53 server5 marker2[21877]: [127-7] SQL_QUERY5_part6
> Aug 11 11:34:53 server5 marker2[21872]: [182-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 LOG:  duration: 0.262 ms, LOG Bind pdo_stmt_0000001d: SQL_QUERY3_part1
> Aug 11 11:34:53 server5 marker2[21872]: [182-2] SQL_QUERY3_part2$a
> Aug 11 11:34:53 server5 marker2[21872]: [182-3] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 DETAILS:  parametrs: $a = 'xyz'
> Aug 11 11:34:53 server5 marker2[21872]: [183-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 LOG:  do pdo_stmt_0000001d: SQL_QUERY3_part1
> Aug 11 11:34:53 server5 marker2[21872]: [183-2] SQL_QUERY3_part2$a
> Aug 11 11:34:53 server5 marker2[21872]: [183-3] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 DETAILS:  parametrs: $a = 'xyz'
> Aug 11 11:34:53 server5 marker2[21881]: [38-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  duration: 0.172 ms, LOG Bind pdo_stmt_00000005: SQL_QUERY4$a$b$c
> Aug 11 11:34:53 server5 marker2[21881]: [38-2] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 DETAILS:  parametrs: $a = '123', $b = '456', $c = '789'
> Aug 11 11:34:53 server5 marker2[21878]: [89-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62679)  Proc ID: 21878  app_name3 LOG:  operator: SQL_QUERY1 pdo_stmt_0000000d
> Aug 11 11:34:53 server5 marker2[21881]: [39-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  do pdo_stmt_00000005: SQL_QUERY4$a$b$c
> Aug 11 11:34:53 server12 marker10[16792]: [15471-1] 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(61603)  Proc ID: 16792  [n/d] LOG:  duration: 0.371 ms
> Aug 11 11:34:53 server12 marker10[15948]: [20762-1] 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(61135)  Proc ID: 15948  [n/d] LOG:  operator: SQL_QUERY6_part1
> Aug 11 11:34:53 server12 marker10[15948]: [20762-2] SQL_QUERY6_part2
> Aug 11 11:34:53 server12 marker10[15948]: [20762-3] SQL_QUERY6_part3
> Aug 11 11:34:53 server12 marker10[15948]: [20762-4] SQL_QUERY6_part4
> Aug 11 11:34:53 server5 marker2[21881]: [39-2] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 DETAILS:  parametrs: $a = '123', $b = '456', $c = '789'
> Aug 11 11:34:53 server5 marker2[21878]: [90-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62679)  Proc ID: 21878  app_name3 LOG:  duration: 0.037 ms
> Aug 11 11:34:53 server5 marker2[21872]: [184-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 LOG:  duration: 0.056 ms
> Aug 11 11:34:53 server5 marker2[21881]: [40-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  duration: 0.048 ms
> Aug 11 11:34:53 server14 marker10[7185]: [14663-1] 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(39067)  Proc ID: 7185  [n/d] LOG:  operator: SQL_QUERY7
> Aug 11 11:34:53 server5 marker2[21877]: [128-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62677)  Proc ID: 21877  app_name4 LOG:  duration: 0.097 ms, LOG Bind pdo_stmt_00000014: 
> Aug 11 11:34:53 server5 marker2[21877]: [128-2] SQL_QUERY5_part1
> Aug 11 11:34:53 server5 marker2[21877]: [128-3] SQL_QUERY5_part2
> Aug 11 11:34:53 server5 marker2[21877]: [128-4] SQL_QUERY5_part3
> Aug 11 11:34:53 server5 marker2[21877]: [128-5] SQL_QUERY5_part4
> Aug 11 11:34:53 server5 marker2[21877]: [128-6] SQL_QUERY5_part5
> Aug 11 11:34:53 server5 marker2[21877]: [128-7] SQL_QUERY5_part6
> Aug 11 11:34:53 server5 marker2[21877]: [129-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62677)  Proc ID: 21877  app_name4 LOG:  do pdo_stmt_00000014: 
> Aug 11 11:34:53 server5 marker2[21877]: [129-2] SQL_QUERY5_part1
> Aug 11 11:34:53 server5 marker2[21877]: [129-3] SQL_QUERY5_part2
> Aug 11 11:34:53 server5 marker2[21877]: [129-4] SQL_QUERY5_part3
> Aug 11 11:34:53 server5 marker2[21877]: [129-5] SQL_QUERY5_part4
> Aug 11 11:34:53 server5 marker2[21877]: [129-6] SQL_QUERY5_part5
> Aug 11 11:34:53 server5 marker2[21877]: [129-7] SQL_QUERY5_part6
> Aug 11 11:34:53 server5 marker2[21877]: [130-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62677)  Proc ID: 21877  app_name4 LOG:  duration: 0.039 ms
> Aug 11 11:34:53 server5 marker2[21872]: [185-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 LOG:  operator: SQL_QUERY1 pdo_stmt_0000001d
> Aug 11 11:34:53 server5 marker2[21872]: [186-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 LOG:  duration: 0.040 ms
> Aug 11 11:34:53 server12 marker10[15948]: [20763-1] 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(61135)  Proc ID: 15948  [n/d] LOG:   duration: 0.971 ms
> Aug 11 11:34:53 server14 marker10[7185]: [14664-1] 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(39067)  Proc ID: 7185  [n/d] LOG:   duration: 0.889 ms

and I want the next result:

> composition               | result
> -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
> [35-1] + [36-1]           | Aug 11 11:34:53 server5 marker2[21881]: [35-1] 2016-08-11 11:34:53.021 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  operator: SQL_QUERY1 pdo_stmt_00000004 2016-08-11 11:34:53.021 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  duration: 0.032 ms
> [29-1] + [30-1]           | Aug 11 11:34:53 server8 marker3[19238]: [29-1] 2016-08-11 11:34:53.020 MSK  User: user2  Database: my_db2  Host: 192.168.50.11(17050)  Proc ID: 19238  app_name2 LOG:  operator: SQL_QUERY1 pdo_stmt_00000002 2016-08-11 11:34:53.020 MSK  User: user2  Database: my_db2  Host: 192.168.50.11(17050)  Proc ID: 19238  app_name2 LOG:  duration: 0.036 ms
> [85-1]                    | Aug 11 11:34:53 server5 marker2[21878]: [85-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62679)  Proc ID: 21878  app_name3 LOG:  duration: 0.118 ms, разбор pdo_stmt_0000000d: SQL_QUERY2
> [86-1]                    | Aug 11 11:34:53 server5 marker2[21878]: [86-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62679)  Proc ID: 21878  app_name3 LOG:  duration: 0.335 ms, LOG Bind pdo_stmt_0000000d: SQL_QUERY2
> [87-1] + [88-1]           | Aug 11 11:34:53 server5 marker2[21878]: [87-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62679)  Proc ID: 21878  app_name3 LOG:  do pdo_stmt_0000000d: SQL_QUERY2 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62679)  Proc ID: 21878  app_name3 LOG:  duration: 0.067 ms
> [125-1] + [126-1]         | Aug 11 11:34:53 server5 marker2[21877]: [125-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62677)  Proc ID: 21877  app_name4 LOG:  operator: SQL_QUERY1 pdo_stmt_00000013 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62677)  Proc ID: 21877  app_name4 LOG:  duration: 0.039 ms
> [181-1] + [181-2]	  | Aug 11 11:34:53 server5 marker2[21872]: [181-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 LOG:  duration: 0.123 ms, разбор pdo_stmt_0000001d: SQL_QUERY3_part1 SQL_QUERY3_part2$a
> [18189-1] + [18190-1]     | Aug 11 11:34:53 server1 marker10[29370]: [18189-1] 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(26091)  Proc ID: 29370  [n/d] LOG:  operator: SQL_QUERY4 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(26091)  Proc ID: 29370  [n/d] LOG:  duration: 0.247 ms
> [37-1]                    | Aug 11 11:34:53 server5 marker2[21881]: [37-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  duration: 0.057 ms, разбор pdo_stmt_00000005: SQL_QUERY4$a$b$c
> [127-(1-7)]               | Aug 11 11:34:53 server5 marker2[21877]: [127-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62677)  Proc ID: 21877  app_name4 LOG:  duration: 0.056 ms, разбор pdo_stmt_00000014: SQL_QUERY5_part1 SQL_QUERY5_part2 SQL_QUERY5_part3 SQL_QUERY5_part4 SQL_QUERY5_part5 SQL_QUERY5_part6
> [15470-(1-4)] + [15471-1] | Aug 11 11:34:53 server12 marker10[16792]: [15470-1] 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(61603)  Proc ID: 16792  [n/d] LOG:  operator: SQL_QUERY8_part1 SQL_QUERY8_part2 SQL_QUERY8_part3 SQL_QUERY8_part4 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(61603)  Proc ID: 16792  [n/d] LOG:  duration: 0.371 ms
> [182-(1-3)]               | Aug 11 11:34:53 server5 marker2[21872]: [182-1] 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 LOG:  duration: 0.262 ms, LOG Bind pdo_stmt_0000001d: SQL_QUERY3_part1 SQL_QUERY3_part2$a 2016-08-11 11:34:53.022 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 DETAILS:  parametrs: $a = 'xyz'
> [183-(1-3)] + [184-1]     | Aug 11 11:34:53 server5 marker2[21872]: [183-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 LOG:  do pdo_stmt_0000001d: SQL_QUERY3_part1 SQL_QUERY3_part2$a 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 DETAILS:  parametrs: $a = 'xyz' 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 LOG:  duration: 0.056 ms
> [38-(1-2)]                | Aug 11 11:34:53 server5 marker2[21881]: [38-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  duration: 0.172 ms, LOG Bind pdo_stmt_00000005: SQL_QUERY4$a$b$c 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 DETAILS:  parametrs: $a = '123', $b = '456', $c = '789'
> [39-(1-2)] + [40-1]       | Aug 11 11:34:53 server5 marker2[21881]: [39-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  do pdo_stmt_00000005: SQL_QUERY4$a$b$c 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 DETAILS:  parametrs: $a = '123', $b = '456', $c = '789' 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  duration: 0.048 ms
> [89-1]+[90-1]             | Aug 11 11:34:53 server5 marker2[21878]: [89-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62679)  Proc ID: 21878  app_name3 LOG:  operator: SQL_QUERY1 pdo_stmt_0000000d 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62679)  Proc ID: 21878  app_name3 LOG:  duration: 0.037 ms
> [20762-(1-4)]+[20763-1]   | Aug 11 11:34:53 server12 marker10[15948]: [20762-1] 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(61135)  Proc ID: 15948  [n/d] LOG:  operator: SQL_QUERY6_part1 SQL_QUERY6_part2 SQL_QUERY6_part3 SQL_QUERY6_part4 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(61135)  Proc ID: 15948  [n/d] LOG:   duration: 0.971 ms
> [14663-1]+[14664-1]       | Aug 11 11:34:53 server14 marker10[7185]: [14663-1] 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(39067)  Proc ID: 7185  [n/d] LOG:  operator: SQL_QUERY7 2016-08-11 11:34:53.021 MSK  User: user3  Database: my_db3  Host: 192.168.5.34(39067)  Proc ID: 7185  [n/d] LOG:   duration: 0.889 ms
> [128-(1-7)]               | Aug 11 11:34:53 server5 marker2[21877]: [128-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62677)  Proc ID: 21877  app_name4 LOG:  duration: 0.097 ms, LOG Bind pdo_stmt_00000014: SQL_QUERY5_part1 SQL_QUERY5_part2 SQL_QUERY5_part3 SQL_QUERY5_part4 SQL_QUERY5_part5 SQL_QUERY5_part6
> [129-(1-7)] + [130-1]     | Aug 11 11:34:53 server5 marker2[21877]: [129-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62677)  Proc ID: 21877  app_name4 LOG:  do pdo_stmt_00000014: SQL_QUERY5_part1 SQL_QUERY5_part2 SQL_QUERY5_part3 SQL_QUERY5_part4 SQL_QUERY5_part5 SQL_QUERY5_part6 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62677)  Proc ID: 21877  app_name4 LOG:  duration: 0.039 ms
> [185-1]+[186-1]           | Aug 11 11:34:53 server5 marker2[21872]: [185-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 LOG:  operator: SQL_QUERY1 pdo_stmt_0000001d 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.12(62667)  Proc ID: 21872  app_name5 LOG:  duration: 0.040 ms

And if possible, it is better that it:
> [35-1] + [36-1]           | Aug 11 11:34:53 server5 marker2[21881]: [35-1] 2016-08-11 11:34:53.021 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  operator: SQL_QUERY1 pdo_stmt_00000004 2016-08-11 11:34:53.021 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  duration: 0.032 ms
It looks like this:
> [35-1] + [36-1]           | Aug 11 11:34:53 server5 marker2[21881]: [35-1] 2016-08-11 11:34:53.021 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  operator: SQL_QUERY1 pdo_stmt_00000004 duration: 0.032 ms

And that:
> [39-(1-2)] + [40-1]       | Aug 11 11:34:53 server5 marker2[21881]: [39-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  do pdo_stmt_00000005: SQL_QUERY4$a$b$c 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 DETAILS:  parametrs: $a = '123', $b = '456', $c = '789' 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  duration: 0.048 ms

looks like this:
> [39-(1-2)] + [40-1]       | Aug 11 11:34:53 server5 marker2[21881]: [39-1] 2016-08-11 11:34:53.023 MSK  User: user1  Database: my_db1  Host: 192.168.7.11(57557)  Proc ID: 21881  app_name1 LOG:  do pdo_stmt_00000005: SQL_QUERY4$a$b$c DETAILS:  parametrs: $a = '123', $b = '456', $c = '789' duration: 0.048 ms

Please help me and I will be very grateful to you.

**Comment by fbaligand** [comment]
> [39-(1-2)] + [40-1] | Aug 11 11:34:53 server5 marker2[21881]: [39-1] 2016-08-11 11:34:53.023 MSK User: user1 Database: my_db1 Host: 192.168.7.11(57557) Proc ID: 21881 app_name1 LOG: do pdo_stmt_00000005: SQL_QUERY4$a$b$c 2016-08-11 11:34:53.023 MSK User: user1 Database: my_db1 Host: 192.168.7.11(57557) Proc ID: 21881 app_name1 DETAILS: parametrs: $a = '123', $b = '456', $c = '789' 2016-08-11 11:34:53.023 MSK User: user1 Database: my_db1 Host: 192.168.7.11(57557) Proc ID: 21881 app_name1 LOG: duration: 0.048 ms

First important question : in line above, what are values which compose aggregate "task_id" ?

**Comment by simpleuser99** [comment]
For accurate results I suppose it must be some value:
proc id  (example - [21881] or Proc ID: 21881)
source port (example - 57557)
number of line and part of line (example [39-1])
and may be Database

**Comment by fbaligand** [comment]
First, sorry for my late answer.
Second, it seems we don't speak about the same thing.
A "task_id" is composed of one or several fields making each of your "composition result lines" unique.

However :
- if we join "proc id", "source port" and "Database" ; we have the same values at line 1 and line 15 in your composition results. So this threesome is not a unique identifier for each aggregated line
- for one aggregated line, you have several couples "number of line and part of line". So it doesn't identify one aggregated line

So could you give me the values which compose a unique task_id ?

**Comment by simpleuser99** [comment]
Thanks for the help. It was possible to solve this problem on their own, with the optional aggregates to the fact that you gave me earlier.

**Comment by fbaligand** [comment]
Nice news :)

**Comment by fbaligand** [comment]
If your problem is solved, could you close this issue ?
