### ISSUE TITLE
Feature request: different timeout values by task_id

### ISSUE THREAD

**Issue by doingitbigdata** [logstash-plugins/logstash-filter-aggregate#42]
Currently the timeout parameter is global across multiple aggregrate tasks with different task_ids. I would like to request that this be changed such that different task_ids can have different timeout values. 

Currently I have low volume tasks where I would like to set the timeout to a large number and conversely there are high volume tasks where I would like to set the timeout smaller to alleviate on memory usage.

**Comment by fbaligand** [comment]
Hi @doingitbigdata 
I just released a new version which fixes your issue !
Hope you'll enjoy it !

**Comment by doingitbigdata** [comment]
@fbaligand Great. Thanks!

**Comment by fbaligand** [comment]
Nice news that you enjoy it !
So I close the issue.
