### ISSUE TITLE
Support of Logstash 5

### ISSUE THREAD

**Issue by mrauter** [logstash-plugins/logstash-filter-aggregate#45]
When I try to install the plugin with Logstash 5 (rc1 or beta1) I get the following error:

https://gist.github.com/mrauter/c52b2a77c873f46e94827c8d11cfd219

**Comment by fbaligand** [comment]
Hi @mrauter,

Actually, aggregate plugin is not yet compatible with Logstash 5. 
But I currently work on this issue, and it should be soon released !

**Comment by mrauter** [comment]
Thank you!

**Comment by fbaligand** [comment]
@mrauter 
This issue has just been fixed with release v2.5.0.
Tell me if it works fine for  you.

**Comment by fbaligand** [comment]
No feedback after one week.
I close the issue.
