### ISSUE TITLE
Map failure after too many log lines

### ISSUE THREAD

**Issue by DenVrede** [logstash-plugins/logstash-filter-aggregate#49]
Hey :)

it seems like there is a problem when the logfile exceeds a specific amount of lines. 
I made a config where i search the lines for a word, when its found i insert a count in the map.
In the final event i add a field with the value of the count. 

I tried it with 3 different files.

test.txt has 1000006 lines, it works like intended.
second_text.txt has 1980448 lines, and the pattern i look for is at the end of the file. In the final event the field is not included.
third_text.txt has 1980448 lined, and the pattern i look for is in the first half of the file. In the final event the field is not included.

I attached everything needed.

[test.txt](https://github.com/logstash-plugins/logstash-filter-aggregate/files/603018/test.txt)
[third_text.txt](https://github.com/logstash-plugins/logstash-filter-aggregate/files/603017/third_text.txt)
[second_text.txt](https://github.com/logstash-plugins/logstash-filter-aggregate/files/603019/second_text.txt)
[logstash_conf.txt](https://github.com/logstash-plugins/logstash-filter-aggregate/files/603020/logstash_conf.txt)

Unfortunately we have a lot of Logfiles which exceed 3000000 lines per file.

Could you look into it? Thanks!

**Comment by DenVrede** [comment]
I'm dumb as fuck. Sorry. I should increase timeout time....

**Comment by fbaligand** [comment]
@DenVrede 
Nice to see that you solve your problem for yourself :)
