### ISSUE TITLE
Logstash-filter-aggregate (2.5.0) fails with latest logstash (>=5.0.2)

### ISSUE THREAD

**Issue by jeslopalo** [logstash-plugins/logstash-filter-aggregate#51]
Hi,

after update logstash from 5.0.0 to 5.0.2 my pipeline fails when aggregating events with logstash-filter-aggregate.  

Is something changed with aggragate syntax?  It's a compatibility issue?

```
    Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
    SystemStackError: stack level too deep
        synchronize at org/jruby/ext/thread/Mutex.java:149
             filter at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-aggregate-2.5.0/lib/logstash/filters/aggregate.rb:427
       multi_filter at /usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:156
               each at org/jruby/RubyArray.java:1613
       multi_filter at /usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:153
       multi_filter at /usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:41
         initialize at (eval):441
               each at org/jruby/RubyArray.java:1613
         initialize at (eval):432
               call at org/jruby/RubyProc.java:281
        filter_func at (eval):302
       filter_batch at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:260
               call at org/jruby/RubyProc.java:281
               each at /usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:186
               each at org/jruby/RubyHash.java:1342
               each at /usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:185
       filter_batch at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:258
        worker_loop at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:246
      start_workers at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:225

```

Thank you,

Jesús López

**Comment by iti888** [comment]
I got stack level too deep error if I use
                event.to_hash.each do |key,value|
                    map[key] = value unless map.has_key?(key)
                    map[key] << value if map[key].is_a?(Array)
                end
I used an extra arrary to get around this problem. eg. (map['address_id'] is extra)
		map['address'] ||= []
		map['address_id'] ||= []
		if !map['address_id'].include?(event.get('address_id')) then
		       	map['address_id'] << event.get('address_id')
        	       	map['address'] << {'address_id' => event.get('address_id'),		
				'street' => event.get('street')}
		end
Any other better solution?

**Comment by fbaligand** [comment]
First, it's very surprising that you get error `SystemStackError: stack level too deep` with your first code solution. It is not a recursive code that led to a long stack.

Then, your second solution is finally less generic but indeed more optimized than first one.
Instead of browsing all event keys, you directly get the one you search for.

I have no other better solution.

**Comment by fbaligand** [comment]
Given that you finally solve your problem, are you OK to close this issue ?

**Comment by iti888** [comment]
Sorry, I did not own this issue. I just happened to have the same error and comment on it.

Sent from Yahoo Mail on Android 
 
  On Sat, Dec 10, 2016 at 10:40, Fabien Baligand<notifications@github.com> wrote:   
Given that you finally solve your problem, are you OK to close this issue ?

**Comment by fbaligand** [comment]
@jeslopalo 
I'm a little bit embarrassed with this issue because :
1. I don't arrive to reproduce it
2. it's not related to aggregate plugin itself, as aggregate plugin don't make long stack calls
3. `stack level too deep` is a weird error

That said, to be able to help you, can you provide your exact aggregate plugin configuration ?

**Comment by jeslopalo** [comment]
Hi @fbaligand !

I'm sorry but I have not been here for a few days.

I'm going to try your suggestions now (upgrading to latest logstash). After that I will try to reduce my configuration to a minimum so I can copy it here.

Thanks!

**Comment by jeslopalo** [comment]
@fbaligand 

I have reproduced it with this example:

```
input {
    stdin {}
}
filter {
    grok {
        match => { "message" => "%{WORD:country_name} - %{WORD:town_name}" }
    }
    aggregate {
        task_id => "%{country_name}"
        code => "
            map['town_name'] ||= []
            event.to_hash.each do |key,value|
                map[key] = value unless map.has_key?(key)
                map[key] << value if map[key].is_a?(Array)
            end
        "
        push_previous_map_as_event => true
        push_map_as_event_on_timeout => true
        timeout => 5
        timeout_tags => ['aggregated']
    }

    if "aggregated" not in [tags] {
        drop {}
    }
}
output {
    stdout { codec => "rubydebug" }
}

```

And then, when I execute it, and force the aggregation:
```
The stdin plugin is now waiting for input:
Spain - Madrid
Spain - Barcelona
France - Paris
SystemStackError: stack level too deep
    synchronize at org/jruby/ext/thread/Mutex.java:149
         filter at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-aggregate-2.5.0/lib/logstash/filters/aggregate.rb:427
   multi_filter at /usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:156
           each at org/jruby/RubyArray.java:1613
   multi_filter at /usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:153
   multi_filter at /usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:41
    filter_func at (eval):95
   filter_batch at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:260
           call at org/jruby/RubyProc.java:281
           each at /usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:186
           each at org/jruby/RubyHash.java:1342
           each at /usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:185
   filter_batch at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:258
    worker_loop at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:246
  start_workers at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:225
```

But if I wait for the timeout, then the error is a bit different (although mutex-related);
```
The stdin plugin is now waiting for input:
Spain - Madrid
Spain - Barcelona
SystemStackError: stack level too deep
               delete_if at org/jruby/RubyHash.java:1642
     remove_expired_maps at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-aggregate-2.5.0/lib/logstash/filters/aggregate.rb:540
             synchronize at org/jruby/ext/thread/Mutex.java:149
     remove_expired_maps at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-aggregate-2.5.0/lib/logstash/filters/aggregate.rb:538
                   flush at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-aggregate-2.5.0/lib/logstash/filters/aggregate.rb:524
                   flush at /usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:58
              initialize at (eval):46
                    call at org/jruby/RubyProc.java:281
           flush_filters at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:447
                    each at org/jruby/RubyArray.java:1613
           flush_filters at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:446
  flush_filters_to_batch at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:489
             worker_loop at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:249
           start_workers at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:225
```

I'm using **Ubuntu 16.04.1 LTS xenial** if it were important.

I'm going to update logstash to see if that works out!


Thanks!

**Comment by jeslopalo** [comment]
Hi again @fbaligand 

I just installed the latest version (5.1.1) and unfortunately I get the same behavior.

**Comment by fbaligand** [comment]
Hi @jeslopalo 

I have good news for you !

- First, I managed to reproduce your problem
- But better, I found the problem and the solution !

The problem : since version 5.0.2, when an event is created, it has now by default, an empty array for `tags` field. Before, until you explicitly add a tag, `tags` field was not created in the event.
And `tags` is a very special case : it is the only case where you copy an array into an array.

The aggregate `code` solution : 
``` ruby
            map['town_name'] ||= []
            event.to_hash.each do |key,value|
                map[key] = value unless map.has_key?(key)
                map[key] << value if map[key].is_a?(Array) and !value.is_a?(Array)
            end
```

To finish, just a last advice : 
Don't use both `push_previous_map_as_event => true` and `push_map_as_event_on_timeout => true`
These 2 options are for different use cases and must not be used together.

**Comment by fbaligand** [comment]
=> I will update the samples in documentation with this fixed code sample.

**Comment by fbaligand** [comment]
Docs updated !

**Comment by jeslopalo** [comment]
Hi @fbaligand !

Great! Thank you very much for your work!

I have tried it and it works perfectly. I close the issue.

And thanks for the advice. I use 'aggregate' to load a database into elasticsearch. I thought that if I didn't use 'push_map_as_event_on_timeout' , the last aggregated event would never be loaded, but I see that it does.

Regards

**Comment by fbaligand** [comment]
@jeslopalo 
Nice to see it solves your problem !

For info :
- `push_previous_map_as_event` is a very specific option for your need : import data from jdbc input plugin. 
- `push_map_as_event_on_timeout` is more generic use : when you have no explicit end event and you have interlaced ids. This option is really less memory efficient than `push_previous_map_as_event` : with push_previous_map_as_event, you have maximum one task map in memory. Here, maps are removed only when timeout occurs.

**Comment by jeslopalo** [comment]
Thanks @fbaligand and great work!

**Comment by fbaligand** [comment]
It's a pleasure to see it helps :)
