### ISSUE TITLE
How to add nested fields in the aggregate?

### ISSUE THREAD

**Issue by iti888** [logstash-plugins/logstash-filter-aggregate#56]
I have the following data:
{ "key":1, "field1":.., .."fieldn":.., "address":"1 street"}
{ "key":1, "field1":.., .."fieldn":.., "address":"2 street"}
...
{ "key":1, "field1":.., .."fieldn":.., "address":"n street"}
My intended out is:
{ "key":1, "field1":.., .."fieldn":.., "address":{"address":"1 street",...,"address":"n street"}}

I know I can use the following to get the intended output:
aggregate{
task_id =>  "%{key}"
code => "
...
map['address'] ||= []
map['address'] << {'address' => event.get('address')}
...
}      
But, the resulted document does not have a nested address but a property of address.
How do I make it a nested document instead of a property?

Thanks

**Comment by fbaligand** [comment]
Mmhh, your intended out is invalid json : 
You cannot have several times the field "address" in a structure

I mean 
"structure": { "address": "a1", "address": "a2" }

**Comment by iti888** [comment]
My mistake, the code output should be "address":[{"address":"1 street"},...,{"address":"n street"}].
The above code work correctly for displaying the result in ES. Only problem is that it is a property not nested type.

**Comment by fbaligand** [comment]
Ok, so if I understand well, with the aggregate filter above, you get the right output structure.
But you don't have the expected mapping type (nested) in elasticsearch. Right ?

**Comment by iti888** [comment]
Correct.

**Comment by fbaligand** [comment]
OK, so in that case :
- this is not a aggregate plugin issue
- you can do it, by defining explicitly elasticsearch mapping for `address` root field, either directly in target index, either in template mapping. The second case is particularly interesting, if you use Logstash elasticsearch output plugin with 1 index per day, and elasticsearch template provided by Logstash.
- Here's the doc to define a nested field in mapping : https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-mapping.html

**Comment by iti888** [comment]
I tried to avoid direct mapping. 
I thought I saw in somewhere you post something like:
map['parent']['child']<<{.....} to get nested field. Or it is not logstash?

**Comment by iti888** [comment]
Looks like the following:
                map['parent'] ||= {}
		map['parent']['child'] ||= []
        	 map['parent']['child'] << {'field1' => event.get('field1'),
        		'field2' => event.get('field2')}
creates in ES like before OK. But still not nested type:
here is the output:
 "parent" : {
   "child" : [
     {
       "field1" : null,
       "file2" : "xxx1"
     },
     {
       "field1" : null,
       "field2" : "xxx2"
     },
     {
       "field1" : null,
       "field2" : "xxx3"
     }
   ]
 }

BTW, could you explain a little bit about template mapping. I thought it was deprecated. Thanks

**Comment by fbaligand** [comment]
Elasticsearch is certainly not deprecated. It is the contrary. For instance, in ES 5.0, they recommend to use templates instead of adding default settings at ES startup (especially number_of_replicas). 
By default, Logstash elasticsearch plugin use a template so that created indices (one per day) have the right mapping. Beats does the same. 

So, you probably already use a "Logstash" template with customized mapping.

**Comment by fbaligand** [comment]
Hi @iti888 ,

Can I consider your question as answered and close the issue ?

**Comment by iti888** [comment]
sure. thanks

**Comment by fbaligand** [comment]
Nice news to see that your issue is solved !
Finally, did you update your es mapping, using Logstash template ?

**Comment by iti888** [comment]
not yet. Will do that later.
