### ISSUE TITLE
 gem

### ISSUE THREAD

**Issue by alasta** [logstash-plugins/logstash-filter-aggregate#59]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by fbaligand** [comment]
@alasta 
Could you describe a real issue or close this issue ?

**Comment by fbaligand** [comment]
Close this issue because contentless

**Comment by alasta** [comment]
sorry it's a bug.
