### ISSUE TITLE
Logstash-aggregate 2.4.0 does not generate aggregate_maps_path file when it stops

### ISSUE THREAD

**Issue by mrchang7** [logstash-plugins/logstash-filter-aggregate#60]
Hi,

I'm a big fan of logstash-aggregate filter and we're using it in the production system. As for this topic, I can see the aggregate version 2.5.1 seems having fixed this bug only with logstash 2.4 or later. But we want to keep the existing logstash 2.3.2 for the time being and hope to have this fix, as a sort of aggregate 2.4.1. Wondering this is is a quick fix and doable sooner or later.

Many thanks!

**Comment by fbaligand** [comment]
I don't make promise but I will try to do it.

**Comment by mrchang7** [comment]
Thanks a lot for your efforts. 

In the meantime, I'm testing LS 2.4.1 with aggregate 2.5.1. That should solve this issue, right? 
BTW, once the map file is generated, as I restart the logstash, it removes the .aggregate file and then dies immediately without error logged. I'm checking my service definition for this job. Anything I have to check?

**Comment by fbaligand** [comment]
Yes, it should solve your issue. 
The fact that file is deleted just after logstash start is normal : aggregate plugin  loads the file in memory and then deletes it. 
If just after that, Logstash dies without error log, that's really surprising and not normal. 

Have you tried to restart after, with no aggregate maps file ?

**Comment by mrchang7** [comment]
You're right. Now it works as expected; restart works. The problem looked with our configuration as managing multiple task_id's with different types of data. We're planing to apply for the FOSS approval to use the higher versions of LS and aggregate plugin. Appreciate your support a lot. :)

**Comment by fbaligand** [comment]
Nice to see it works great for you !

**Comment by fbaligand** [comment]
As you finally use aggregate plugin version 2.5.1, I suppose you don't need anymore this 2.4.1 fix ?
If so, could you close this issue ?

**Comment by mrchang7** [comment]
Right. Thanks for helping with this.
