### ISSUE TITLE
aggregate 2.4.0 issue when using with split plugin

### ISSUE THREAD

**Issue by mrchang7** [logstash-plugins/logstash-filter-aggregate#61]
Hi again,

I'm not sure this issue could be in some way related to the other one I raised. 

Here is my sample code to reproduce it. Sorry but it might not be a very concise example. When the 2.4.0 aggregate plugin is used with split, it looks it does not pass the maps over to the split events. The same code works correct with the lower version. All tested with the same logstash version 2.3.2. Please correct if the code is missing something. 

With the following code run, I tried providing the std input like this (two lines of records):
t1 f1
t2 f2

And then checked if the s_data getting the correct value assigned before split, which is "value". But the result shows 'nil' for this field of s_data. 

```
input {
    stdin {}
}

filter {

    grok { match => { "message" => "%{DATA:t_id} %{DATA:f_id}$" } }

    aggregate {
        task_id => "%{t_id}"
        code => "
                if map['f_ids']
                    map['f_ids'] << event['f_id']
                else
                    map['f_ids'] = [event['f_id']]
                end
                event['f_ids'] = map['f_ids']
                "
    }

    aggregate {
        task_id => "%{f_id}"
        code => "
                map['data'] = 'value'
                event['data'] = map['data']
                "
    }

    if [f_id] == "f2" {
        split {
            field => "f_ids"
            target => "s_id"
        }
        aggregate {
            task_id => "%{s_id}"
            code => "
                    event['s_data'] = map['data']
                    "
        }
    }

}

output {
    stdout { codec => rubydebug }
}
```

**Comment by fbaligand** [comment]
Actually, since version 2.4.0, if taskid pattern is not the same, aggregate map is not shared. 
If you want sharing, you have to use the same taskid pattern so have to keep same value in same field name

**Comment by mrchang7** [comment]
Okay, I see. Then I will try to following the rule. It would be nicer to have that in the document. Currently, it says for the task_id, "This value must uniquely identify the task in the system."

Thanks for your quick help!

**Comment by fbaligand** [comment]
You are right. 
I have to explain it in documentation. 

That said, I truly think you should use version 2.3.1 : 
- in this version, aggregate maps are nicely stored to configured path at shutdown 
- and there is not this "new behavior" which annoy you.

**Comment by mrchang7** [comment]
As I made the patterns the same even with the field names, it worked as before. Can I ask why you made this change? Wondering.. the value of task_id should matter if the map keeps based on it. 

Thanks!

**Comment by mrchang7** [comment]
The problem using 2.3.1 is we have multiple task_id's and like to set different time_out values to them.

**Comment by fbaligand** [comment]
To allow this new 2.4 feature (timeout options per task id pattern), I had to tie aggregate maps to their taskid pattern ; so that timeout management for one task id pattern process only associated aggregate maps.

**Comment by mrchang7** [comment]
That makes sense. Thanks!

**Comment by fbaligand** [comment]
@mrchang7 
As it was a simple question, and the question is answered, could you close this issue ?
