### ISSUE TITLE
How can I fix the problem

### ISSUE THREAD

**Issue by myheed** [logstash-plugins/logstash-filter-aggregate#66]
A_start
A_1
A_2
B_start
B_1
A_end
B_2
B_end

**Comment by fbaligand** [comment]
aggregate plugin solves exactly this kind of problem (interlaced logs). It is its aim. 
Example # 1 in aggregate documentation is the solution to your problem.

**Comment by myheed** [comment]
Thank you !

**Comment by myheed** [comment]
but only the first line and the last line have id

**Comment by fbaligand** [comment]
I believed that "A" and "B" where your task ids.
If not, what are "A" and "B" ?

**Comment by fbaligand** [comment]
No answer, so I close the issue.
