### ISSUE TITLE
Filter does not always check map correctly after timeout

### ISSUE THREAD

**Issue by MattiL** [logstash-plugins/logstash-filter-aggregate#69]
inactivity_timeout is not working as I expected. I have the configuration below where I tried to make Logstash maintain a heartbeat state in map. I expect Logstash to evict map at timeout but maybe it does not. Logstash does not always seem to recover from timeout but remains in an error state where it does not react to new activity by tagging an event with 'heartbeatStateChanged' but stays inactive.
- Version: logstash-filter-aggregate 2.6.0, Logstash 5.3.1
- Operating System: CentOS Linux release 7.3.1611
- Config File:
/etc/logstash/logstash.yml:
`# pipeline.workers: 1`
making Logstash "pipeline.workers"=>16
```
     if [host] and [application] {
         aggregate {
             task_id => "%{host}%{application}"
             code => "
                 if map['heartbeat'] != 'OK'
                     event.tag('heartbeatStateChanged')
                     event.set('heartbeat', 'OK')
                     event.set('heartbeat_severity', 1)
                 end
                 map['heartbeat'] = 'OK'
                 map['host'] = event.get('host')
                 map['application'] = event.get('application')
                 map['component'] = 'main'
                 map['component_id'] = 'main'
             "
             timeout_code => "
                 event.tag('heartbeatStateChanged')
                 event.set('heartbeat_severity', 2)
                 event.set('heartbeat', 'ALARM')
                 event.set('message', '2 minutes elapsed since the last heartbeat.')
             "
             push_map_as_event_on_timeout => true
             inactivity_timeout => 120
             timeout => 999999999
         }
     } 
```
- Steps to Reproduce:
Feed log lines to Logstash from Filebeat. Sometimes a timeout occurs. After the timeout, new activity occurs with the same task_id. Then Logstash should tag 'heartbeatStateChanged' but it does not always do so.

**Comment by MattiL** [comment]
After more thorough investigation, I did not find any error in the filter.

**Comment by fbaligand** [comment]
@MattiL 
Nice to see it finally works as expected for you !
