### ISSUE TITLE
NoMethodError with Logstash 5.6.4

### ISSUE THREAD

**Issue by jbwl** [logstash-plugins/logstash-filter-aggregate#75]
I upgraded to LS 5.6.4 and with no configuration change on the aggregate filter, I see this error:

```[2017-11-15T18:53:48,011][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/usr/local/Cellar/logstash/5.6.4/libexec/vendor/bundle/jruby/1.9/gems/logstash-filter-aggregate-2.7.1/lib/logstash/filters/aggregate.rb:267:in `extract_previous_map_as_event'", "/usr/local/Cellar/logstash/5.6.4/libexec/vendor/bundle/jruby/1.9/gems/logstash-filter-aggregate-2.7.1/lib/logstash/filters/aggregate.rb:303:in `flush'", "/usr/local/Cellar/logstash/5.6.4/libexec/logstash-core/lib/logstash/filter_delegator.rb:63:in `flush'", "(eval):19:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "/usr/local/Cellar/logstash/5.6.4/libexec/logstash-core/lib/logstash/pipeline.rb:551:in `flush_filters'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/local/Cellar/logstash/5.6.4/libexec/logstash-core/lib/logstash/pipeline.rb:550:in `flush_filters'", "/usr/local/Cellar/logstash/5.6.4/libexec/logstash-core/lib/logstash/pipeline.rb:592:in `flush_filters_to_batch'", "/usr/local/Cellar/logstash/5.6.4/libexec/logstash-core/lib/logstash/pipeline.rb:392:in `worker_loop'", "/usr/local/Cellar/logstash/5.6.4/libexec/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}```

**Comment by fbaligand** [comment]
Hi @jbwl, 

Well, it seems we've got an issue here :)

So, first, to fix quickly your problem, I invite you to uninstall aggregate filter, then reinstall it forcing the version to 2.6.4.

Then, so that I can reproduce your issue (and so fix it), can you give me details about you get this error ? What is your aggregate configuration and when this error occurs ? At startup/shutdown/when a special new event occurs ? etc...

**Comment by jbwl** [comment]
Using version 2.6.4 did fix the error. Thank you.

This is the config that I am using:

```
aggregate {
       task_id => "%{invoiceid}"
       add_tag => [ "data" ]
       code => "
         map['systemdate_iso8601'] = event.get('systemdate_iso8601')
         map['invoiceid'] = event.get('invoiceid')
         map['invoicemode'] = event.get('invoicemode')
         map['invoicedirection'] = event.get('invoicedirection')
         map['invoicefactor'] = event.get('invoicefactor')
         map['creditfactor'] = event.get('creditfactor')
         map['duedate'] = event.get('duedate')
         map['itemcount'] = event.get('itemcount')
         map['parcelcount'] = event.get('parcelcount')
		 map['goodsamount1'] = event.get('goodsamount1')
         map['invoiceno'] = event.get('invoiceno')
         map['invoicedate'] = event.get('invoicedate')
         map['systemdate'] = event.get('systemdate')
         map['customerid'] = event.get('customerid')
         map['customerno'] = event.get('customerno')
         map['invoiceitems'] ||= []
         map['invoiceitems'] << { 'articleid' => event.get('invoiceitems.articleid'),
                                  'quantity' => event.get('invoiceitems.quantity'),
                                  'sales' => event.get('invoiceitems.sales'),
                                  'naturals' => event.get('invoiceitems.naturals'),
                                  'promos' => event.get('invoiceitems.promos'),
                                  'credits' => event.get('invoiceitems.credits'),
                                  'payedsales' => event.get('invoiceitems.payedsales'),
                                  'sreturns' => event.get('invoiceitems.sreturns'),
                                  'defects' => event.get('invoiceitems.defects')
         }
         event.cancel()
       "
       push_previous_map_as_event => true
       timeout => 3
}
```
As an explanation what I use it for: I am indexing invoice data in ES. The data is stored in a relational database, one table for invoice metadata, one table for invoice linedata. I am using the filter to add the linedata as a json array to the metadata.

**Comment by fbaligand** [comment]
Hi @jbwl 

I just released v2.7.2, which should resolve your issue.

**Comment by jbwl** [comment]
Confimed. Thank you!!

**Comment by fbaligand** [comment]
@jbwl 
Nice to see it fixes your problem !
