### ISSUE TITLE
Event order is not right when Aggregate Multiple line

### ISSUE THREAD

**Issue by haninkyu** [logstash-plugins/logstash-filter-aggregate#82]
- Version: 6.1.2
- Operating System: centos6

hi! I want to make a json data from application's log, so I try to use an elk to my java application.
but I have a problem while aggregate multiple lines which has same task id into one json data.
Explain to an example.

My application's log print a information on different lines over different lines And 
Multiple tasks are working at the same time, so each line of application's log are mixed. for example-

12:30:03.02 task1 endpoint : /board/write
12:30:01.02 task1 client_ip : 1.1.1.1
12:30:03.02 task2 endpoint : /board/read
12:30:04.02 task1 data : {title:"hello world", content:"hellow elk"}
12:30:05.02 task3 result : success
12:30:06.02 task2 data : {uid:"1", token:"asdf"} 
12:30:07.02 task2 result : success
12:30:08.02 task1 result : fail
............
..skip...
............
12:52:00.01 task1 endpoint : /board/write
12:52:00.18 task1 client_ip : 2.2.2.2
12:52:00.22 task1 data : {title:"hello world2", content:"hellow elk2"}
12:52:01.02 task2 client_ip : 3.3.3.3
12:52:01.86 task1 result : success

I have a such like log. and I expect to make a json data by using logstash.
{
  task_id:"1"
  information : [
    endpoint:"/board/write",
    client_ip:"1.1.1.1",
    data:"{title:"hello world", content:"hellow elk"}",
    result:"fail"
  ]
  start_time:"12:30:03.02"
  end_time:"12:30:08.02"
}
...........
..skip..
...........
{
  task_id:"1"
  information : [
    endpoint:"/board/write"
    client_ip:"2.2.2.2",
    data:"{title:"hello world2", content:"hellow elk2"}",
    result:"success"
  ]
  start_time:"12:52:00.01"
  end_time:"12:52:01.86"
}

so i use aggregate filter. if each line has a 'result', 'end_of_task' is true. other case, set the key and value(client_ip and 2.2.2.2) to map. and it works.

but sometimes it makes a problem like that.

{
  task_id:"1"
  information : [null]
  start_time:null
  end_time:"12:30:08.02"
}
...........
..skip..
...........
{
  task_id:"1"
  information : [
     endpoint:"/board/write",
    client_ip:"1.1.1.1",
    data:"{title:"hello world", content:"hellow elk"}",
    result:"fail"
    endpoint:"/board/write"
    client_ip:"2.2.2.2",
    data:"{title:"hello world2", content:"hellow elk2"}",
    result:"success"
  ]
  start_time:"12:30:03.02"
  end_time:"12:52:01.86"
}

and I check logstash debug log, It has been confirmed that the order of the lines is shuffled from 'pipeline receive'. 
give me a hint or some opinion..!

**Comment by fbaligand** [comment]
Hi @haninkyu 

I see 2 things : 
- first, so that you are sure that events are processed in the right order, you have to set pipeline workers count to 1. You can do it by setting this command line argument : `-w 1`
- then, it's really surprising you get your first 'task 1' aggregation without field 'result'. If you tell this field is the condition to get 'end_of_task', the only way you get 1 aggregation without field 'result' is to have a timeout or maybe a code exception (which means you have '_aggregateerror' tag).

**Comment by haninkyu** [comment]
hi @fbaligand. I appreciate ur help :)
I test with pipeline worker option and I confirm to receive events in right order 👍
(and my timeout is not a problem. it's very long time)

and I have a more quesion. Does filebeat have a similar setting? I got a problem like this.

[2018-02-22T10:47:43,491][DEBUG][logstash.pipeline        ] filter received {"event"=>{"offset"=>832321760, ...
[2018-02-22T10:47:43,502][DEBUG][logstash.pipeline        ] filter received {"event"=>{"offset"=>831987311, ...
[2018-02-22T10:47:43,502][DEBUG][logstash.pipeline        ] filter received {"event"=>{"offset"=>831987471, ...
[2018-02-22T10:47:43,502][DEBUG][logstash.pipeline        ] filter received {"event"=>{"offset"=>831987594, ...
[2018-02-22T10:47:43,502][DEBUG][logstash.pipeline        ] filter received {"event"=>{"offset"=>831987738, ...

I think that filebeat doesn't send a event in right order(check an offset value)

**Comment by fbaligand** [comment]
Normally, it process events in right order. 
But I’m not a specialist. 
Maybe you could open an issue on filebeat’s github

**Comment by haninkyu** [comment]
@fbaligand ok I see.
I confirm it's not faulting the aggregate filter. input thread read log's line right order, but filter receives events out of order. thank ur help!

**Comment by fbaligand** [comment]
Happy to see you appreciate my help :)
I close this issue.
