### ISSUE TITLE
Want to get startTime and endTime of an event.

### ISSUE THREAD

**Issue by maitray16** [logstash-plugins/logstash-filter-aggregate#84]
I wanted to aggregate logs which have no start and end event. But I want to know when was the first time the log of that type came in and the last time it came in a timeout duration. 

For example - 

Logs

13-Mar-2018 22:54:22.281 google.com
13-Mar-2018 22:54:22.282 google.com
13-Mar-2018 22:54:22.283 google.com
13-Mar-2018 22:54:22.284 google.com
13-Mar-2018 22:54:22.285 google.com
13-Mar-2018 22:54:22.286 twitter.com
13-Mar-2018 22:54:22.287 twitter.com
13-Mar-2018 22:54:22.288 twitter.com

Current Filter - 

```
aggregate {
		task_id => "%{query}"
	       code => "map['occurrences'] ||= 0; map['occurrences'] += 1; map['query'] = event.get('query');map['end_time'] = event.get('@timestamp');
	       push_map_as_event_on_timeout => true
	       timeout_task_id_field => "query_id"
	       timeout => 30 # 30 sec timeout
	       timeout_tags => ['_summary']
	       timeout_code => "event.set('duration', '30')"
}

```
Output - 

```
{
  "_index": "domxx",
  "_id": "",
  "_version": 1,
  "_source": {
    "occurrences": 3320,
    "duration": "30",
    "query_id": "google.com",
    "end_time": "2018-03-15T21:20:40.130Z",
    "tags": [
      "_summary"
    ]
  }
}

```

In this scenario the end_time works fine since the field gets overwritten but is there any way to find start_time ?

Thanks

**Comment by mrchang7** [comment]
why don't you keep the start time in a map as exposing it using event.set on each log? Will need to check if the map variable for the start time has been initialized or not...

**Comment by fbaligand** [comment]
@maitray16 
You can compute start time using this code : 
`map['start_time'] ||= event.get('@timestamp');`

This would set 'start_time' field only if it is not already assigned.

**Comment by maitray16** [comment]
Hey @fbaligand Yup, that works. Thanks a lot. 
Also I have noticed that type doesn't get detected when using aggregate plugin. I used mutate to change those. But I think that should be in a different thread ?

**Comment by fbaligand** [comment]
Yes, could you close this issue (as it is solved) and open a new issue for your type issue.
