### ISSUE TITLE
Can't set timeout value based on event filed or metadata

### ISSUE THREAD

**Issue by exanta** [logstash-plugins/logstash-filter-aggregate#91]
Hi,

I would like to set filter settings - aggregate filter timeout value - based on event field or metadata.
I have converted metadata to integer:

mutate { convert => { "[@metadata][taskID_timeout]" => "integer" } }
and next try to use this value in aggregate filter (set timeout value):

aggregate {
task_id => "%{taskID}"
code => "
map['problem_duration'] = event.get('epoc')
"
push_map_as_event_on_timeout => true
timeout_task_id_field => "event_id"
timeout => "%{[@metadata][taskID_timeout]}"
timeout_tags => ['_aggregatetimeout']
timeout_code => "event.set('problem_duration', map['problem_duration'])"
}
but logstash don't start and log error:

[ERROR] 2018-08-31 08:28:02.768 [Converge PipelineAction::Create] aggregate - Invalid setting for aggregate filter plugin:

filter {
aggregate {
This setting must be a number
Expected number, got "%{[@metadata][taskID_timeout]}" (type %{[@metadata][taskID_timeout]})
timeout => "%{[@metadata][taskID_timeout]}"
...
}
}
I know that it is possible to set string settings for example elasticsearch output settings:

action => "%{[@metadata][action]}"
document_id => "%{[@metadata][_id]}"
but what with integer settings?

Based on yaauie aswer on logasth github Aggregate Filter Plugin requires that timeout be a number, and does not allow input from the event to control the timeout.

I think it could be very useful have possibility to set timeout  for each event type (each taskID). 

BR
TM

**Comment by exanta** [comment]
Hi,

I will attempt to describe you my usecase. 
My logstash process events . Simple describe.  event has:

- timestamp
- event_id (uniq event identifier)
- problem_event_id (identifier of problem event)
- event_type ( this field describe type of event).  

I want to correlate resolution event  to problem event (problem_event_id of resolution event equal to event_id of problem event) and add to resolution event new field (problem_duration - difference between timestamps) and it works. Next I want send problem event to output only if I don't get resoution event after specific timeout. If I get resolution before specific timeout I want to send to output only resoltion event with problem_duration. 
The problem is that I want to defined different timeout for each event_type.
I'm still working on my logstash config and I will send you it after some progres ;-)

I think your idea with map_meta.timeout looks good!!

BR
TM

**Comment by fbaligand** [comment]
Hi @exanta 

I'm happy to announce that aggregate plugin v2.9.0 is out !
And it fixes your issue !
You can see change log here : https://github.com/logstash-plugins/logstash-filter-aggregate/blob/master/CHANGELOG.md
And doc about the feature you wait for here : https://github.com/logstash-plugins/logstash-filter-aggregate/blob/master/docs/index.asciidoc#code

Feel free to ask questions and give feedback about the feature !

**Comment by exanta** [comment]
Hi, 

Great!! I will try new features and update you ASAP.

BR
TM
