### ISSUE TITLE
How can i aggregate fix amount of events ?

### ISSUE THREAD

**Issue by wuyexixi** [logstash-plugins/logstash-filter-aggregate#92]
Is any way to aggregate fix amount of events (like 100 events) then send as one event. not just by a fixed time windows?

- Version:2.2
- Operating System:Centos
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by fbaligand** [comment]
Hi @wuyexixi 

This feature is not available for now.
I think we can achieve this, using the same mechanism than what I plan for issue #91 : 
- add a new `map_meta` variable available in `code` block
- in `code` block you can do : `map_meta.timeout = 0` if you reach 100 particular events

So your Logstash configuration would look like : 
```
aggregate {
taskid => "%{mytaskid}"
code => "
map['aggregated_events'] ||= 0
map['aggregated_events']++
map_meta.timeout = 0 if map['aggregated_events'] == 100
"
push_map_as_event_on_timeout => true
}
```

Would it answer your need ?

**Comment by wuyexixi** [comment]
Very helpful, Thank you very much.

**Comment by wuyexixi** [comment]
HI, fbaligand,
    I tried your suggestion but system responses [2018-10-29T11:44:10,734][ERROR][logstash.filters.aggregate] Aggregate exception occurred {:error=>#<NameError: undefined local variable or method `map_meta' for #<LogStash::Filters::Aggregate:0x690a7d72>, did i miss something ? tks.

aggregate {
    task_id => "%{project}"
    code => "
              map['count'] ||= 0
              map['project'] = event.get('project')
              map['groupdata'] ||= []
              map['groupdata'] << event.get('data')
              map['count'] += 1
              map_meta.timeout = 0 if map['count'] == 10
              event.cancel()
            "
    push_previous_map_as_event => true
    push_map_as_event_on_timeout => true
    timeout => 10
  }

**Comment by fbaligand** [comment]
Well, the feature is not yet available. 
I’m currently implementing it. 
I will notify you here as soon as it will be available.

**Comment by wuyexixi** [comment]
Got it. Tks a lot.

**Comment by fbaligand** [comment]
Hi @wuyexixi 

I'm happy to announce that aggregate plugin v2.9.0 is out !
And it fixes your issue !
You can see change log here : https://github.com/logstash-plugins/logstash-filter-aggregate/blob/master/CHANGELOG.md
And doc about the feature you wait for here : https://github.com/logstash-plugins/logstash-filter-aggregate/blob/master/docs/index.asciidoc#code

Feel free to ask questions and give feedback about the feature !

**Comment by fbaligand** [comment]
All you have to do is :
bin/logstash-plugin update logstash-filter-aggregate

**Comment by wuyexixi** [comment]
Got it. Tks.
