### ISSUE TITLE
aggregate nested not work

### ISSUE THREAD

**Issue by dutengfei789** [logstash-plugins/logstash-filter-aggregate#99]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: 5.6
- Operating System: win 10
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

Thanks to the aggregate filter provided by the author for giving me ideas. Input plugin, I am using jdbc as the input source, and when filtering aggregated, follow your third example setting, timeout. Because the data cannot be sorted after reading data from jdbc, the data is not sorted in the normal order. When I do a one-to-many mapping, the same task id may be distributed on different pages, resulting in less than expected number of collections in my mapping set. . How do I set the timeout to ensure that the data is indexed correctly? Help. . .

```
input {
  stdin {

  }
  jdbc {
	
	  jdbc_connection_string => "jdbc:postgresql://xxxxxxx/edw"
	  jdbc_user => "xxxx"
	  jdbc_password => "xxxxxx"
	  jdbc_default_timezone => "Asia/Shanghai"
	  jdbc_driver_library => "D:\logstash-5.6.16\lib\postgresql-8.3-603.jdbc4.jar"
	  jdbc_driver_class => "org.postgresql.Driver"
	  jdbc_paging_enabled => "true"
	  jdbc_page_size => "1000"
	  statement => "SELECT
	SO.billno flowNo,
	SO.market shopCode,
	S.shopname,
	S.cityname,
	SO.ought_pay totalmoney,
	SO.sale_date filDate,
	MB.UUID memberId,
	SI.itemname gName,
	SI.itemcode gdCode,
	SI.qty,
	SI.price rtlPrc,
	SI.sale_amount realAmt,
	SI.total_discount favAmt 
FROM
	dw_saleorderdetail SI
	JOIN dw_saleorderstemp SO ON SI.BILLNO = SO.BILLNO
	JOIN dw_shop S ON S.shopid = SO.market
	JOIN dw_member_orderinfo MB ON SO.memberID = MB.memberID 
	AND SO.market <> 'SHDS' 
	AND SI.SALE_DATE = SO.SALE_DATE 
	AND SI.SALE_DATE BETWEEN '2019-05-01' 
	AND '2019-05-02' 
	AND SO.SALE_DATE BETWEEN '2019-05-01' 
	AND '2019-05-02' "
  }
}

filter{

    aggregate {
        task_id=>"%{flowno}"
        code=>"
            map['esId']=event.get('flowno')
            map['BuyItems'] ||= []
			map['shopCode'] =event.get('shopcode')
			map['shopName'] =event.get('shopname')
			map['cityName'] = event.get('cityname')
			map['flowNo'] =event.get('flowno')
			map['totalMoney']=event.get('totalmoney')
			map['filDate'] = event.get('fildate')
			map['memberId'] = event.get('memberid')
            map['BuyItems'] << {'gName'=> event.get('gname'),'gdCode'=>event.get('gdcode'),'qty'=>event.get('qty'),'rtlPrc'=>event.get('rtlprc'),'realAmt'=>event.get('realamt'),'favAmt'=>event.get('favamt')}
            event.cancel()
        "
        push_previous_map_as_event=>true
		timeout => 3600
		
    }
	
	mutate {
		remove_field => ["@version","@timestamp"]
		
	}
	
	

}

output {
  elasticsearch {
	  hosts => "localhost:9200"
	  index => "offline_order"
	  document_id => "%{esId}"
	  document_type =>"doc"
	  routing => "2019"
	  
  }
  stdout {
	codec => rubydebug 
  }
}

```
![image](https://user-images.githubusercontent.com/40482075/59010221-1c554180-8863-11e9-9bba-3cf5a2443421.png)

**Comment by dutengfei789** [comment]
I tried to add sorting by time in jdbc and it doesn't work.

**Comment by fbaligand** [comment]
First, in that case (push_previous_map_as_event), timeout is useful only for last event. For previous events, map is pushed each time task_id value changes. 

Then, when you use push_previous_map_as_event, you have to order jdbc statement by task_id. There is no workaround. 
Given your task_id, I invite you to order your sql query by flowNo. 
It should work way better!

**Comment by dutengfei789** [comment]
Because the amount of data is too large, I need to use the distribution function of jdbc. When I use the jdbc_paging_enabled=true, I still can't sort. The jdbc input official documentation also says so, so I am confused now.
One way to do this is to set the number of pages to be large enough, but this does not solve the underlying problem.
The second method is that I compare the rtlprc in buyItems with totalMoney and output it when it is equal, but I don't know how to achieve it.

The official jdbc documentation is as follows：
![image](https://user-images.githubusercontent.com/40482075/59018474-8d532400-8878-11e9-9ea4-352297f95732.png)

**Comment by fbaligand** [comment]
When you say that your data is too large, you speak about how many events?
Do you have "-w 1" setting at Logstash startup?

If you don't master sql query order, you can't use push_previous_map_as_event feature, as it is based on order.
Instead of this, you can use push_map_as_event_on_timeout=true, and set inactivity_timeout=5.
It will group the data per 5s.
I must prevent you: it will consume a lot of memory...
Because, lots of aggregated maps will be loaded in memory at the same time.

Then on elasticsearch, you set action=update, doc_as_upsert=true.
And in script, you write something like context._source.BuyItems.add(event.get('BuyItems')[0])
Or better, a for loop, to add every BuyItems.
Globally, it allows to first create the Elasticsearch document, then to update the Elasticsearch document.

And a totally different option, would be to have a first jdbc pipeline that outputs to a Kafka topic, with one partition per flowNo.
Then add another pipeline with several threads (worker threads), that have a kafka input and aggregate filter.
It will let to have a partition per flowNo and a thread per flowNo.
It could work, but I'm not sure.

**Comment by dutengfei789** [comment]
我按照你第一种方法成功了，但是我只修改了output的设置。非常感谢。
```
 elasticsearch {
	  hosts => "localhost:9200"
	  index => "offline_order_2019"
	  document_id => "%{esId}"
	  document_type =>"doc"
	  doc_as_upsert => true
	  action => "update"
	  # retry_on_conflict => 1000
	  script_type => "inline"
	  script => "
	  for (int i=0 ;i<params.event.get('buyItems').length;++i)
	  {ctx._source.buyItems.add(params.event.get('buyItems')[i])}
	  "  
  }
```

**Comment by fbaligand** [comment]
Great!

Thanks for the share!

**Comment by dutengfei789** [comment]
When the data is now guided, there will be duplicate data. In the attribute mapping of a collection type, it is assumed that there should be 3, but there are 9 actually, and the other 6 are duplicate data, but not all data is like this. A small part will repeat, which makes me confused.

 I tried to reduce the paging size, but still can't solve the data when exporting.

 I guess it is added repeatedly when the map is used. I use map_action => "create_or_update" End_of_task => true instead of push_previous_map_as_event, but will not output. 

Now I don't know what to do, can you give me some advice?
